// Mocks generated by Mockito 5.4.4 from annotations
// in marty_authenticator/test/tests_app_wrapper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i13;

import 'package:flutter/foundation.dart' as _i17;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:marty_authenticator/interfaces/repo/introduction_repository.dart'
    as _i9;
import 'package:marty_authenticator/interfaces/repo/settings_repository.dart'
    as _i8;
import 'package:marty_authenticator/interfaces/repo/token_repository.dart'
    as _i5;
import 'package:marty_authenticator/model/enums/ec_key_algorithm.dart' as _i15;
import 'package:marty_authenticator/model/riverpod_states/introduction_state.dart'
    as _i10;
import 'package:marty_authenticator/model/riverpod_states/settings_state.dart'
    as _i2;
import 'package:marty_authenticator/model/tokens/token.dart' as _i7;
import 'package:marty_authenticator/repo/secure_storage.dart' as _i18;
import 'package:marty_authenticator/utils/allow_screenshot_utils.dart' as _i16;
import 'package:marty_authenticator/utils/ecc_utils.dart' as _i14;
import 'package:marty_authenticator/utils/rsa_utils.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:pointycastle/export.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettingsState_0 extends _i1.SmartFake implements _i2.SettingsState {
  _FakeSettingsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRSAPublicKey_1 extends _i1.SmartFake implements _i3.RSAPublicKey {
  _FakeRSAPublicKey_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRSAPrivateKey_2 extends _i1.SmartFake implements _i3.RSAPrivateKey {
  _FakeRSAPrivateKey_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAsymmetricKeyPair_3<
  B extends _i3.PublicKey,
  V extends _i3.PrivateKey
>
    extends _i1.SmartFake
    implements _i3.AsymmetricKeyPair<B, V> {
  _FakeAsymmetricKeyPair_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeECPublicKey_4 extends _i1.SmartFake implements _i3.ECPublicKey {
  _FakeECPublicKey_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeECPrivateKey_5 extends _i1.SmartFake implements _i3.ECPrivateKey {
  _FakeECPrivateKey_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_6 extends _i1.SmartFake implements _i4.IOSOptions {
  _FakeIOSOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_7 extends _i1.SmartFake
    implements _i4.AndroidOptions {
  _FakeAndroidOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_8 extends _i1.SmartFake implements _i4.LinuxOptions {
  _FakeLinuxOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_9 extends _i1.SmartFake
    implements _i4.WindowsOptions {
  _FakeWindowsOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_10 extends _i1.SmartFake implements _i4.WebOptions {
  _FakeWebOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_11 extends _i1.SmartFake implements _i4.MacOsOptions {
  _FakeMacOsOptions_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_12 extends _i1.SmartFake
    implements _i4.FlutterSecureStorage {
  _FakeFlutterSecureStorage_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenRepository extends _i1.Mock implements _i5.TokenRepository {
  @override
  _i6.Future<_i7.Token?> loadToken(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadToken, [id]),
            returnValue: _i6.Future<_i7.Token?>.value(),
            returnValueForMissingStub: _i6.Future<_i7.Token?>.value(),
          )
          as _i6.Future<_i7.Token?>);

  @override
  _i6.Future<List<_i7.Token>> loadTokens() =>
      (super.noSuchMethod(
            Invocation.method(#loadTokens, []),
            returnValue: _i6.Future<List<_i7.Token>>.value(<_i7.Token>[]),
            returnValueForMissingStub: _i6.Future<List<_i7.Token>>.value(
              <_i7.Token>[],
            ),
          )
          as _i6.Future<List<_i7.Token>>);

  @override
  _i6.Future<bool> saveOrReplaceToken(_i7.Token? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrReplaceToken, [token]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<T>> saveOrReplaceTokens<T extends _i7.Token>(
    List<T>? tokens,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrReplaceTokens, [tokens]),
            returnValue: _i6.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i6.Future<List<T>>.value(<T>[]),
          )
          as _i6.Future<List<T>>);

  @override
  _i6.Future<bool> deleteToken(_i7.Token? token) =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, [token]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<T>> deleteTokens<T extends _i7.Token>(List<T>? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTokens, [tokens]),
            returnValue: _i6.Future<List<T>>.value(<T>[]),
            returnValueForMissingStub: _i6.Future<List<T>>.value(<T>[]),
          )
          as _i6.Future<List<T>>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i8.SettingsRepository {
  @override
  _i6.Future<bool> saveSettings(_i2.SettingsState? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.SettingsState> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i6.Future<_i2.SettingsState>.value(
              _FakeSettingsState_0(this, Invocation.method(#loadSettings, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.SettingsState>.value(
              _FakeSettingsState_0(this, Invocation.method(#loadSettings, [])),
            ),
          )
          as _i6.Future<_i2.SettingsState>);
}

/// A class which mocks [IntroductionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntroductionRepository extends _i1.Mock
    implements _i9.IntroductionRepository {
  @override
  _i6.Future<bool> saveCompletedIntroductions(
    _i10.IntroductionState? introductions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCompletedIntroductions, [introductions]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i10.IntroductionState> loadCompletedIntroductions() =>
      (super.noSuchMethod(
            Invocation.method(#loadCompletedIntroductions, []),
            returnValue: _i6.Future<_i10.IntroductionState>.value(
              _i11.dummyValue<_i10.IntroductionState>(
                this,
                Invocation.method(#loadCompletedIntroductions, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i10.IntroductionState>.value(
              _i11.dummyValue<_i10.IntroductionState>(
                this,
                Invocation.method(#loadCompletedIntroductions, []),
              ),
            ),
          )
          as _i6.Future<_i10.IntroductionState>);
}

/// A class which mocks [RsaUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockRsaUtils extends _i1.Mock implements _i12.RsaUtils {
  @override
  _i3.RSAPublicKey deserializeRSAPublicKeyPKCS1(String? keyStr) =>
      (super.noSuchMethod(
            Invocation.method(#deserializeRSAPublicKeyPKCS1, [keyStr]),
            returnValue: _FakeRSAPublicKey_1(
              this,
              Invocation.method(#deserializeRSAPublicKeyPKCS1, [keyStr]),
            ),
            returnValueForMissingStub: _FakeRSAPublicKey_1(
              this,
              Invocation.method(#deserializeRSAPublicKeyPKCS1, [keyStr]),
            ),
          )
          as _i3.RSAPublicKey);

  @override
  String serializeRSAPublicKeyPKCS1(_i3.RSAPublicKey? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#serializeRSAPublicKeyPKCS1, [publicKey]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeRSAPublicKeyPKCS1, [publicKey]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeRSAPublicKeyPKCS1, [publicKey]),
            ),
          )
          as String);

  @override
  _i3.RSAPublicKey deserializeRSAPublicKeyPKCS8(String? keyStr) =>
      (super.noSuchMethod(
            Invocation.method(#deserializeRSAPublicKeyPKCS8, [keyStr]),
            returnValue: _FakeRSAPublicKey_1(
              this,
              Invocation.method(#deserializeRSAPublicKeyPKCS8, [keyStr]),
            ),
            returnValueForMissingStub: _FakeRSAPublicKey_1(
              this,
              Invocation.method(#deserializeRSAPublicKeyPKCS8, [keyStr]),
            ),
          )
          as _i3.RSAPublicKey);

  @override
  String serializeRSAPublicKeyPKCS8(_i3.RSAPublicKey? key) =>
      (super.noSuchMethod(
            Invocation.method(#serializeRSAPublicKeyPKCS8, [key]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeRSAPublicKeyPKCS8, [key]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeRSAPublicKeyPKCS8, [key]),
            ),
          )
          as String);

  @override
  String serializeRSAPrivateKeyPKCS1(_i3.RSAPrivateKey? key) =>
      (super.noSuchMethod(
            Invocation.method(#serializeRSAPrivateKeyPKCS1, [key]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeRSAPrivateKeyPKCS1, [key]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeRSAPrivateKeyPKCS1, [key]),
            ),
          )
          as String);

  @override
  _i3.RSAPrivateKey deserializeRSAPrivateKeyPKCS1(String? keyStr) =>
      (super.noSuchMethod(
            Invocation.method(#deserializeRSAPrivateKeyPKCS1, [keyStr]),
            returnValue: _FakeRSAPrivateKey_2(
              this,
              Invocation.method(#deserializeRSAPrivateKeyPKCS1, [keyStr]),
            ),
            returnValueForMissingStub: _FakeRSAPrivateKey_2(
              this,
              Invocation.method(#deserializeRSAPrivateKeyPKCS1, [keyStr]),
            ),
          )
          as _i3.RSAPrivateKey);

  @override
  bool verifyRSASignature(
    _i3.RSAPublicKey? publicKey,
    _i13.Uint8List? signedMessage,
    _i13.Uint8List? signature,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyRSASignature, [
              publicKey,
              signedMessage,
              signature,
            ]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<_i3.AsymmetricKeyPair<_i3.RSAPublicKey, _i3.RSAPrivateKey>>
  generateRSAKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#generateRSAKeyPair, []),
            returnValue:
                _i6.Future<
                  _i3.AsymmetricKeyPair<_i3.RSAPublicKey, _i3.RSAPrivateKey>
                >.value(
                  _FakeAsymmetricKeyPair_3<_i3.RSAPublicKey, _i3.RSAPrivateKey>(
                    this,
                    Invocation.method(#generateRSAKeyPair, []),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<
                  _i3.AsymmetricKeyPair<_i3.RSAPublicKey, _i3.RSAPrivateKey>
                >.value(
                  _FakeAsymmetricKeyPair_3<_i3.RSAPublicKey, _i3.RSAPrivateKey>(
                    this,
                    Invocation.method(#generateRSAKeyPair, []),
                  ),
                ),
          )
          as _i6.Future<
            _i3.AsymmetricKeyPair<_i3.RSAPublicKey, _i3.RSAPrivateKey>
          >);

  @override
  String createBase32Signature(
    _i3.RSAPrivateKey? privateKey,
    _i13.Uint8List? dataToSign,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBase32Signature, [privateKey, dataToSign]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#createBase32Signature, [
                privateKey,
                dataToSign,
              ]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#createBase32Signature, [
                privateKey,
                dataToSign,
              ]),
            ),
          )
          as String);

  @override
  _i13.Uint8List createRSASignature(
    _i3.RSAPrivateKey? privateKey,
    _i13.Uint8List? dataToSign,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRSASignature, [privateKey, dataToSign]),
            returnValue: _i13.Uint8List(0),
            returnValueForMissingStub: _i13.Uint8List(0),
          )
          as _i13.Uint8List);
}

/// A class which mocks [EccUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockEccUtils extends _i1.Mock implements _i14.EccUtils {
  @override
  String serializeECPublicKey(_i3.ECPublicKey? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#serializeECPublicKey, [publicKey]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeECPublicKey, [publicKey]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeECPublicKey, [publicKey]),
            ),
          )
          as String);

  @override
  _i3.ECPublicKey deserializeECPublicKey(String? ecPublicKey) =>
      (super.noSuchMethod(
            Invocation.method(#deserializeECPublicKey, [ecPublicKey]),
            returnValue: _FakeECPublicKey_4(
              this,
              Invocation.method(#deserializeECPublicKey, [ecPublicKey]),
            ),
            returnValueForMissingStub: _FakeECPublicKey_4(
              this,
              Invocation.method(#deserializeECPublicKey, [ecPublicKey]),
            ),
          )
          as _i3.ECPublicKey);

  @override
  String serializeECPrivateKey(_i3.ECPrivateKey? ecPrivateKey) =>
      (super.noSuchMethod(
            Invocation.method(#serializeECPrivateKey, [ecPrivateKey]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeECPrivateKey, [ecPrivateKey]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#serializeECPrivateKey, [ecPrivateKey]),
            ),
          )
          as String);

  @override
  _i3.ECPrivateKey deserializeECPrivateKey(String? ecPrivateKey) =>
      (super.noSuchMethod(
            Invocation.method(#deserializeECPrivateKey, [ecPrivateKey]),
            returnValue: _FakeECPrivateKey_5(
              this,
              Invocation.method(#deserializeECPrivateKey, [ecPrivateKey]),
            ),
            returnValueForMissingStub: _FakeECPrivateKey_5(
              this,
              Invocation.method(#deserializeECPrivateKey, [ecPrivateKey]),
            ),
          )
          as _i3.ECPrivateKey);

  @override
  String signWithPrivateKey(_i3.ECPrivateKey? privateKey, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#signWithPrivateKey, [privateKey, message]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#signWithPrivateKey, [privateKey, message]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#signWithPrivateKey, [privateKey, message]),
            ),
          )
          as String);

  @override
  _i3.AsymmetricKeyPair<_i3.ECPublicKey, _i3.ECPrivateKey> generateKeyPair(
    _i15.EcKeyAlgorithm? keyAlgorithm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateKeyPair, [keyAlgorithm]),
            returnValue:
                _FakeAsymmetricKeyPair_3<_i3.ECPublicKey, _i3.ECPrivateKey>(
                  this,
                  Invocation.method(#generateKeyPair, [keyAlgorithm]),
                ),
            returnValueForMissingStub:
                _FakeAsymmetricKeyPair_3<_i3.ECPublicKey, _i3.ECPrivateKey>(
                  this,
                  Invocation.method(#generateKeyPair, [keyAlgorithm]),
                ),
          )
          as _i3.AsymmetricKeyPair<_i3.ECPublicKey, _i3.ECPrivateKey>);

  @override
  bool validateSignature(
    _i3.ECPublicKey? publicKey,
    String? signature,
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateSignature, [
              publicKey,
              signature,
              message,
            ]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [AllowScreenshotUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllowScreenshotUtils extends _i1.Mock
    implements _i16.AllowScreenshotUtils {
  @override
  _i6.Future<bool> allowScreenshots() =>
      (super.noSuchMethod(
            Invocation.method(#allowScreenshots, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> disallowScreenshots() =>
      (super.noSuchMethod(
            Invocation.method(#disallowScreenshots, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> toggleAllowScreenshots(bool? oldState) =>
      (super.noSuchMethod(
            Invocation.method(#toggleAllowScreenshots, [oldState]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i4.FlutterSecureStorage {
  @override
  _i4.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_6(this, Invocation.getter(#iOptions)),
            returnValueForMissingStub: _FakeIOSOptions_6(
              this,
              Invocation.getter(#iOptions),
            ),
          )
          as _i4.IOSOptions);

  @override
  _i4.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_7(
              this,
              Invocation.getter(#aOptions),
            ),
            returnValueForMissingStub: _FakeAndroidOptions_7(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i4.AndroidOptions);

  @override
  _i4.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_8(
              this,
              Invocation.getter(#lOptions),
            ),
            returnValueForMissingStub: _FakeLinuxOptions_8(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i4.LinuxOptions);

  @override
  _i4.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_9(
              this,
              Invocation.getter(#wOptions),
            ),
            returnValueForMissingStub: _FakeWindowsOptions_9(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i4.WindowsOptions);

  @override
  _i4.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_10(
              this,
              Invocation.getter(#webOptions),
            ),
            returnValueForMissingStub: _FakeWebOptions_10(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i4.WebOptions);

  @override
  _i4.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_11(
              this,
              Invocation.getter(#mOptions),
            ),
            returnValueForMissingStub: _FakeMacOsOptions_11(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i4.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i17.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i17.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> write({
    required String? key,
    required String? value,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> read({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<bool> containsKey({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> delete({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, String>> readAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> deleteAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i6.Future<bool?>.value(),
            returnValueForMissingStub: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i18.SecureStorage {
  @override
  _i4.FlutterSecureStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFlutterSecureStorage_12(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeFlutterSecureStorage_12(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.FlutterSecureStorage);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get seperator =>
      (super.noSuchMethod(
            Invocation.getter(#seperator),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#seperator),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#seperator),
            ),
          )
          as String);

  @override
  String getFullKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getFullKey, [key]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#getFullKey, [key]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#getFullKey, [key]),
            ),
          )
          as String);

  @override
  _i6.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, String>> readAll() =>
      (super.noSuchMethod(
            Invocation.method(#readAll, []),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> delete({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#key: key}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
