/*
 * privacyIDEA Authenticator
 *
 * Authors: Adam Burdett <adam.burdett@netknights.it>
 *
 * Copyright (c) 2025 NetKnights GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import 'dart:typed_data';

import 'key_manager.dart';

/// MMF Authentication Key Manager Interface.
///
/// Provides authentication-specific key operations built on top of [IKeyManager].
/// This interface handles device identity, session establishment, and
/// challenge-response authentication.
///
/// Key ID namespacing: All keys managed by this interface use the `auth:` prefix.
/// - `auth:device:{deviceId}` - Device identity keys
/// - `auth:session:{sessionId}` - Session establishment keys
/// - `auth:challenge:{challengeId}` - Challenge-response keys
///
/// Marty's credential key management uses `cred:` prefix and is handled
/// separately in the credential domain layer.
abstract class IAuthKeyManager {
  /// The underlying key manager for low-level crypto operations.
  IKeyManager get keyManager;

  /// Generate a new device identity key pair.
  ///
  /// This key is used to prove device identity during authentication flows.
  /// The key is hardware-backed when available and typically requires
  /// biometric authentication for signing operations.
  ///
  /// Returns the public key in JWK format.
  Future<DeviceKeyInfo> generateDeviceKey({
    required String deviceId,
    bool requireBiometric = true,
  });

  /// Get the device's public key for identity verification.
  Future<Uint8List?> getDevicePublicKey(String deviceId);

  /// Sign an authentication challenge.
  ///
  /// Used in challenge-response authentication flows (e.g., push notifications,
  /// device attestation). May trigger biometric authentication.
  Future<Uint8List> signChallenge({
    required String deviceId,
    required Uint8List challenge,
  });

  /// Verify device attestation data.
  ///
  /// Validates that the attestation was generated by a genuine device
  /// with secure hardware. Platform-specific implementation.
  Future<AttestationResult> verifyDeviceAttestation({
    required Uint8List attestation,
    required Uint8List challenge,
  });

  /// Establish an encrypted session with a peer.
  ///
  /// Performs ECDH key agreement to derive shared session keys.
  /// Used for secure credential transport (e.g., ISO 18013-5 mDoc transfer).
  Future<SessionKeys> establishSession({
    required Uint8List peerPublicKey,
    String? sessionId,
  });

  /// Derive a session key from an established session.
  ///
  /// Uses the session's shared secret to derive purpose-specific keys.
  Future<Uint8List> deriveSessionKey({
    required String sessionId,
    required String purpose,
    int keyLength = 32,
  });

  /// Close a session and securely erase session keys.
  Future<void> closeSession(String sessionId);

  /// Check if a device key exists.
  Future<bool> hasDeviceKey(String deviceId);

  /// Delete a device key.
  ///
  /// This is a destructive operation - the device will need to re-register.
  Future<void> deleteDeviceKey(String deviceId);

  /// List all active session IDs.
  Future<List<String>> listActiveSessions();
}

/// Information about a generated device key.
class DeviceKeyInfo {
  /// The device identifier.
  final String deviceId;

  /// The key identifier (with auth: prefix).
  final String keyId;

  /// The public key in JWK format.
  final Uint8List publicKeyJwk;

  /// Whether the key is hardware-backed.
  final bool isHardwareBacked;

  /// Device attestation data (platform-specific).
  final Uint8List? attestation;

  const DeviceKeyInfo({
    required this.deviceId,
    required this.keyId,
    required this.publicKeyJwk,
    required this.isHardwareBacked,
    this.attestation,
  });
}

/// Result of device attestation verification.
class AttestationResult {
  /// Whether the attestation is valid.
  final bool isValid;

  /// The attested device identifier.
  final String? deviceId;

  /// Security level of the attestation.
  final AttestationSecurityLevel securityLevel;

  /// Error message if validation failed.
  final String? error;

  const AttestationResult({
    required this.isValid,
    this.deviceId,
    this.securityLevel = AttestationSecurityLevel.unknown,
    this.error,
  });

  const AttestationResult.invalid(String this.error)
    : isValid = false,
      deviceId = null,
      securityLevel = AttestationSecurityLevel.unknown;
}

/// Security level of device attestation.
enum AttestationSecurityLevel {
  /// Unknown or unavailable.
  unknown,

  /// Software-based attestation (less secure).
  software,

  /// Trusted Execution Environment (TEE).
  tee,

  /// Secure Element or dedicated hardware.
  strongBox,
}

/// Session keys derived from ECDH key agreement.
class SessionKeys {
  /// Session identifier.
  final String sessionId;

  /// Key for encrypting data sent to peer.
  final Uint8List encryptionKey;

  /// Key for decrypting data received from peer.
  final Uint8List decryptionKey;

  /// MAC key for message authentication.
  final Uint8List macKey;

  /// When the session was established.
  final DateTime establishedAt;

  /// Session expiry time.
  final DateTime? expiresAt;

  const SessionKeys({
    required this.sessionId,
    required this.encryptionKey,
    required this.decryptionKey,
    required this.macKey,
    required this.establishedAt,
    this.expiresAt,
  });

  /// Check if the session has expired.
  bool get isExpired => expiresAt != null && DateTime.now().isAfter(expiresAt!);
}

/// Key ID prefix constants for namespace separation.
class AuthKeyPrefix {
  AuthKeyPrefix._();

  /// Prefix for device identity keys.
  static const String device = 'auth:device:';

  /// Prefix for session establishment keys.
  static const String session = 'auth:session:';

  /// Prefix for challenge-response keys.
  static const String challenge = 'auth:challenge:';

  /// Check if a key ID is an authentication key.
  static bool isAuthKey(String keyId) => keyId.startsWith('auth:');

  /// Extract the device ID from a device key ID.
  static String? parseDeviceId(String keyId) {
    if (keyId.startsWith(device)) {
      return keyId.substring(device.length);
    }
    return null;
  }

  /// Extract the session ID from a session key ID.
  static String? parseSessionId(String keyId) {
    if (keyId.startsWith(session)) {
      return keyId.substring(session.length);
    }
    return null;
  }
}
