package it.netknights.piauthenticator.handlers

import com.spruceid.mobile.sdk.rs.AsyncHttpClient
import com.spruceid.mobile.sdk.rs.HttpRequest
import com.spruceid.mobile.sdk.rs.HttpResponse
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.util.concurrent.TimeUnit

/** OkHttp implementation of the callback interface generated by SpruceKit 0.12.11. */
class HttpClientWrapper : AsyncHttpClient {
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .followRedirects(true)
        .followSslRedirects(true)
        .build()

    override suspend fun httpClient(request: HttpRequest): HttpResponse =
        withContext(Dispatchers.IO) {
            val body = if (request.body.isNotEmpty()) {
                request.body.toRequestBody(
                    request.headers.entries
                        .firstOrNull { it.key.equals("content-type", ignoreCase = true) }
                        ?.value
                        ?.toMediaTypeOrNull()
                )
            } else {
                null
            }

            val okHttpRequest = Request.Builder()
                .url(request.url)
                .apply { request.headers.forEach { (name, value) -> header(name, value) } }
                .method(request.method, body)
                .build()

            client.newCall(okHttpRequest).execute().use { response ->
                HttpResponse(
                    statusCode = response.code.toUShort(),
                    headers = response.headers.toMultimap().mapValues { it.value.joinToString(",") },
                    body = response.body?.bytes() ?: byteArrayOf()
                )
            }
        }

    fun shutdown() {
        client.dispatcher.executorService.shutdown()
        client.connectionPool.evictAll()
    }
}
