// Mocks generated by Mockito 5.4.4 from annotations
// in marty_authenticator/test/integration/sprucekit_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:marty_authenticator/services/background_sync_service.dart'
    as _i5;
import 'package:marty_authenticator/services/credential_verification_service.dart'
    as _i2;
import 'package:marty_authenticator/services/presentation_builder_service.dart'
    as _i6;
import 'package:marty_authenticator/services/privacy_analysis_service.dart'
    as _i3;
import 'package:marty_authenticator/services/qr_scanner_service_enhanced.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVerificationResult_0 extends _i1.SmartFake
    implements _i2.VerificationResult {
  _FakeVerificationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePrivacyAnalysisResult_1 extends _i1.SmartFake
    implements _i3.PrivacyAnalysisResult {
  _FakePrivacyAnalysisResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProcessedQRResult_2 extends _i1.SmartFake
    implements _i4.ProcessedQRResult {
  _FakeProcessedQRResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncConfiguration_3 extends _i1.SmartFake
    implements _i5.SyncConfiguration {
  _FakeSyncConfiguration_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncResult_4 extends _i1.SmartFake implements _i5.SyncResult {
  _FakeSyncResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PresentationBuilderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPresentationBuilderService extends _i1.Mock
    implements _i6.PresentationBuilderService {
  MockPresentationBuilderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<Map<String, dynamic>> createPresentation({
    required List<Map<String, dynamic>>? credentials,
    required String? presentationRequest,
    required List<String>? selectedAttributes,
    String? challenge,
    String? domain,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPresentation, [], {
              #credentials: credentials,
              #presentationRequest: presentationRequest,
              #selectedAttributes: selectedAttributes,
              #challenge: challenge,
              #domain: domain,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [CredentialVerificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCredentialVerificationService extends _i1.Mock
    implements _i2.CredentialVerificationService {
  MockCredentialVerificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.VerificationResult> verifyCredential(
    Map<String, dynamic>? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCredential, [credential]),
            returnValue: _i7.Future<_i2.VerificationResult>.value(
              _FakeVerificationResult_0(
                this,
                Invocation.method(#verifyCredential, [credential]),
              ),
            ),
          )
          as _i7.Future<_i2.VerificationResult>);
}

/// A class which mocks [PrivacyAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrivacyAnalysisService extends _i1.Mock
    implements _i3.PrivacyAnalysisService {
  MockPrivacyAnalysisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> initialize({_i3.PrivacyConfiguration? configuration}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#configuration: configuration}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.PrivacyAnalysisResult> analyzeAttributeDisclosure(
    List<String>? requestedAttributes,
    List<Map<String, dynamic>>? matchingCredentials,
    String? presentationRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeAttributeDisclosure, [
              requestedAttributes,
              matchingCredentials,
              presentationRequest,
            ]),
            returnValue: _i7.Future<_i3.PrivacyAnalysisResult>.value(
              _FakePrivacyAnalysisResult_1(
                this,
                Invocation.method(#analyzeAttributeDisclosure, [
                  requestedAttributes,
                  matchingCredentials,
                  presentationRequest,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.PrivacyAnalysisResult>);
}

/// A class which mocks [QRScannerServiceEnhanced].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRScannerServiceEnhanced extends _i1.Mock
    implements _i4.QRScannerServiceEnhanced {
  MockQRScannerServiceEnhanced() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.ProcessedQRResult> processQRCode(String? rawData) =>
      (super.noSuchMethod(
            Invocation.method(#processQRCode, [rawData]),
            returnValue: _i7.Future<_i4.ProcessedQRResult>.value(
              _FakeProcessedQRResult_2(
                this,
                Invocation.method(#processQRCode, [rawData]),
              ),
            ),
          )
          as _i7.Future<_i4.ProcessedQRResult>);
}

/// A class which mocks [BackgroundSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackgroundSyncService extends _i1.Mock
    implements _i5.BackgroundSyncService {
  MockBackgroundSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i5.CredentialSyncInfo> get syncStatus =>
      (super.noSuchMethod(
            Invocation.getter(#syncStatus),
            returnValue: <String, _i5.CredentialSyncInfo>{},
          )
          as Map<String, _i5.CredentialSyncInfo>);

  @override
  List<_i5.SyncResult> get syncHistory =>
      (super.noSuchMethod(
            Invocation.getter(#syncHistory),
            returnValue: <_i5.SyncResult>[],
          )
          as List<_i5.SyncResult>);

  @override
  _i7.Stream<_i5.CredentialSyncInfo> get syncStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncStatusStream),
            returnValue: _i7.Stream<_i5.CredentialSyncInfo>.empty(),
          )
          as _i7.Stream<_i5.CredentialSyncInfo>);

  @override
  _i7.Stream<_i5.SyncResult> get syncResultStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncResultStream),
            returnValue: _i7.Stream<_i5.SyncResult>.empty(),
          )
          as _i7.Stream<_i5.SyncResult>);

  @override
  bool get isSyncActive =>
      (super.noSuchMethod(Invocation.getter(#isSyncActive), returnValue: false)
          as bool);

  @override
  _i5.SyncConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeSyncConfiguration_3(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i5.SyncConfiguration);

  @override
  _i7.Future<void> initialize({_i5.SyncConfiguration? configuration}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#configuration: configuration}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateConfiguration(_i5.SyncConfiguration? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfiguration, [configuration]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.SyncResult> performSync({
    List<String>? credentialIds,
    _i5.SyncPriority? priority = _i5.SyncPriority.medium,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#performSync, [], {
              #credentialIds: credentialIds,
              #priority: priority,
              #force: force,
            }),
            returnValue: _i7.Future<_i5.SyncResult>.value(
              _FakeSyncResult_4(
                this,
                Invocation.method(#performSync, [], {
                  #credentialIds: credentialIds,
                  #priority: priority,
                  #force: force,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.SyncResult>);

  @override
  _i7.Future<List<String>> checkRevocations({List<String>? credentialIds}) =>
      (super.noSuchMethod(
            Invocation.method(#checkRevocations, [], {
              #credentialIds: credentialIds,
            }),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i5.CredentialSyncInfo? getSyncStatus(String? credentialId) =>
      (super.noSuchMethod(Invocation.method(#getSyncStatus, [credentialId]))
          as _i5.CredentialSyncInfo?);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
