// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'credential.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_claim`

/// Parse a raw JSON string into a VerifiableCredential.
Future<VerifiableCredential> parseVerifiableCredential({
  required String json,
}) => RustLib.instance.api.crateApiParseVerifiableCredential(json: json);

/// Parse CBOR bytes into an MDocCredential.
Future<MDocCredential> parseMdocCredential({required List<int> cborBytes}) =>
    RustLib.instance.api.crateApiParseMdocCredential(cborBytes: cborBytes);

/// Parse SD-JWT string into an SdJwtCredential.
Future<SdJwtCredential> parseSdJwtCredential({required String sdJwt}) =>
    RustLib.instance.api.crateApiParseSdJwtCredential(sdJwt: sdJwt);

/// Verify mDoc trust chain from X.509 certificate chain.
Future<TrustInfo> verifyMdocTrustChain({required List<Uint8List> x5Chain}) =>
    RustLib.instance.api.crateApiVerifyMdocTrustChain(x5Chain: x5Chain);

/// Verify and attach trust info to an mDoc credential.
Future<MDocCredential> verifyAndAttachTrust({
  required MDocCredential mdoc,
  required List<Uint8List> x5Chain,
}) => RustLib.instance.api.crateApiVerifyAndAttachTrust(
  mdoc: mdoc,
  x5Chain: x5Chain,
);

/// Group credentials by issuer for stacked display.
Future<List<CredentialGroup>> groupCredentialsByIssuer({
  required List<Credential> credentials,
}) => RustLib.instance.api.crateApiGroupCredentialsByIssuer(
  credentials: credentials,
);

/// Create a selectable credential for presentation UI.
Future<SelectableCredential> createSelectableCredential({
  required Credential credential,
  required PrivacyLevel privacyLevel,
}) => RustLib.instance.api.crateApiCreateSelectableCredential(
  credential: credential,
  privacyLevel: privacyLevel,
);

/// Check if a credential is expired.
Future<bool> isCredentialExpired({required Credential credential}) =>
    RustLib.instance.api.crateApiIsCredentialExpired(credential: credential);

/// Get all claim names from a credential.
Future<List<String>> getCredentialClaims({required Credential credential}) =>
    RustLib.instance.api.crateApiGetCredentialClaims(credential: credential);

/// Serialize a credential to JSON for storage.
Future<String> credentialToJson({required Credential credential}) =>
    RustLib.instance.api.crateApiCredentialToJson(credential: credential);

/// Deserialize a credential from JSON.
Future<Credential> credentialFromJson({required String json}) =>
    RustLib.instance.api.crateApiCredentialFromJson(json: json);
