// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'biometrics.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_provider`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Verify that a probe face image matches a reference face image.
///
/// Both images must be base64-encoded. If `models_dir` is provided and
/// contains ONNX model files, real on-device inference is used; otherwise
/// a mock provider returns deterministic results for testing.
Future<FrbFaceMatchResult> verifyFaceMatch({
  required String referenceImage,
  required String probeImage,
  double? threshold,
  String? modelsDir,
}) => RustLib.instance.api.crateBiometricsVerifyFaceMatch(
  referenceImage: referenceImage,
  probeImage: probeImage,
  threshold: threshold,
  modelsDir: modelsDir,
);

/// Assess the quality of a face image before verification.
///
/// Returns a quality assessment with individual factor scores.
Future<FrbFaceQuality> assessFaceQuality({
  required String image,
  String? modelsDir,
}) => RustLib.instance.api.crateBiometricsAssessFaceQuality(
  image: image,
  modelsDir: modelsDir,
);

/// Estimate the age of the subject in a face image.
///
/// Requires ONNX models — returns an error if models are not available.
Future<FrbAgeEstimate> estimateFaceAge({
  required String image,
  String? modelsDir,
}) => RustLib.instance.api.crateBiometricsEstimateFaceAge(
  image: image,
  modelsDir: modelsDir,
);

/// Age estimation result.
@freezed
sealed class FrbAgeEstimate with _$FrbAgeEstimate {
  const factory FrbAgeEstimate({
    required int estimatedAge,
    required double confidence,
    required int ageRangeLow,
    required int ageRangeHigh,
  }) = _FrbAgeEstimate;
}

/// Result of a face match comparison.
@freezed
sealed class FrbFaceMatchResult with _$FrbFaceMatchResult {
  const factory FrbFaceMatchResult({
    required bool verified,
    required double similarity,
    required double threshold,
    required String provider,
    double? referenceQuality,
    double? probeQuality,
    required BigInt processingTimeMs,
  }) = _FrbFaceMatchResult;
}

/// Quality assessment of a face image.
@freezed
sealed class FrbFaceQuality with _$FrbFaceQuality {
  const factory FrbFaceQuality({
    required double overallScore,
    required bool faceDetected,
    required int faceCount,
    required double sharpness,
    required double brightness,
    required double contrast,
    required double faceSize,
    required double pose,
  }) = _FrbFaceQuality;
}
