// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'biometrics.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `gesture_prompt`, `run_biometric`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BiometricRuntime`, `CachedBiometrics`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Verify that a probe face image matches a reference face image.
///
/// Both images must be base64-encoded. `models_dir` must identify the ONNX
/// model directory. Initialization failures are returned to the caller.
/// Repeated calls reuse one worker/runtime/provider for that directory.
Future<FrbFaceMatchResult> verifyFaceMatch({
  required String referenceImage,
  required String probeImage,
  double? threshold,
  String? modelsDir,
}) => RustLib.instance.api.crateBiometricsVerifyFaceMatch(
  referenceImage: referenceImage,
  probeImage: probeImage,
  threshold: threshold,
  modelsDir: modelsDir,
);

/// Assess the quality of a face image before verification.
///
/// Returns a quality assessment with individual factor scores.
Future<FrbFaceQuality> assessFaceQuality({
  required String image,
  String? modelsDir,
}) => RustLib.instance.api.crateBiometricsAssessFaceQuality(
  image: image,
  modelsDir: modelsDir,
);

/// Estimate the age of the subject in a face image.
///
/// Requires ONNX models — returns an error if models are not available.
Future<FrbAgeEstimate> estimateFaceAge({
  required String image,
  String? modelsDir,
}) => RustLib.instance.api.crateBiometricsEstimateFaceAge(
  image: image,
  modelsDir: modelsDir,
);

/// Create and sign an active-liveness challenge in Rust.
FrbLivenessChallenge createLivenessChallenge({
  required List<String> gestures,
  required BigInt ttlSeconds,
  required String signingSecret,
}) => RustLib.instance.api.crateBiometricsCreateLivenessChallenge(
  gestures: gestures,
  ttlSeconds: ttlSeconds,
  signingSecret: signingSecret,
);

/// Verify a canonical active-liveness challenge and fail closed on expiry,
/// tampering, malformed input, or a wrong key.
bool verifyLivenessChallenge({
  required String nativePayload,
  required String signingSecret,
}) => RustLib.instance.api.crateBiometricsVerifyLivenessChallenge(
  nativePayload: nativePayload,
  signingSecret: signingSecret,
);

/// Apply the canonical active-liveness gesture threshold policy.
bool evaluateLivenessGesture({
  required String gesture,
  double? smilingProbability,
  double? headEulerAngleX,
  double? headEulerAngleY,
}) => RustLib.instance.api.crateBiometricsEvaluateLivenessGesture(
  gesture: gesture,
  smilingProbability: smilingProbability,
  headEulerAngleX: headEulerAngleX,
  headEulerAngleY: headEulerAngleY,
);

/// Finish pending biometric calls and release the cached provider and runtime.
/// A subsequent verification call initializes a new worker.
Future<void> shutdownBiometrics() =>
    RustLib.instance.api.crateBiometricsShutdownBiometrics();

/// Age estimation result.
@freezed
sealed class FrbAgeEstimate with _$FrbAgeEstimate {
  const factory FrbAgeEstimate({
    required int estimatedAge,
    required double confidence,
    required int ageRangeLow,
    required int ageRangeHigh,
  }) = _FrbAgeEstimate;
}

/// Result of a face match comparison.
@freezed
sealed class FrbFaceMatchResult with _$FrbFaceMatchResult {
  const factory FrbFaceMatchResult({
    required bool verified,
    required double similarity,
    required double threshold,
    required String provider,
    double? referenceQuality,
    double? probeQuality,
    required BigInt processingTimeMs,
  }) = _FrbFaceMatchResult;
}

/// Quality assessment of a face image.
@freezed
sealed class FrbFaceQuality with _$FrbFaceQuality {
  const factory FrbFaceQuality({
    required double overallScore,
    required bool faceDetected,
    required int faceCount,
    required double sharpness,
    required double brightness,
    required double contrast,
    required double faceSize,
    required double pose,
  }) = _FrbFaceQuality;
}

/// Signed active-liveness challenge created by the canonical biometric kernel.
@freezed
sealed class FrbLivenessChallenge with _$FrbLivenessChallenge {
  const factory FrbLivenessChallenge({
    required String challengeId,
    required String nonce,
    required String issuedAt,
    required String expiresAt,
    required List<String> gestures,
    required String signature,
    required String nativePayload,
  }) = _FrbLivenessChallenge;
}
