// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'credential.freezed.dart';

@freezed
sealed class Credential with _$Credential {
  const Credential._();

  /// W3C Verifiable Credential
  const factory Credential.verifiableCredential(VerifiableCredential field0) =
      Credential_VerifiableCredential;

  /// ISO 18013-5 mDoc (Mobile Driving License)
  const factory Credential.mDoc(MDocCredential field0) = Credential_MDoc;

  /// SD-JWT Verifiable Credential
  const factory Credential.sdJwt(SdJwtCredential field0) = Credential_SdJwt;
}

/// Grouping of credentials by issuer for stacked display.
class CredentialGroup {
  /// Issuer identifier
  final String issuer;

  /// Display name for the issuer
  final String issuerName;

  /// Credentials from this issuer
  final List<Credential> credentials;

  /// Issuer logo URL
  final String? logoUrl;

  const CredentialGroup({
    required this.issuer,
    required this.issuerName,
    required this.credentials,
    this.logoUrl,
  });

  @override
  int get hashCode =>
      issuer.hashCode ^
      issuerName.hashCode ^
      credentials.hashCode ^
      logoUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CredentialGroup &&
          runtimeType == other.runtimeType &&
          issuer == other.issuer &&
          issuerName == other.issuerName &&
          credentials == other.credentials &&
          logoUrl == other.logoUrl;
}

/// Credential status for revocation checking.
class CredentialStatus {
  /// Status type (e.g., "StatusList2021Entry")
  final String statusType;

  /// Status list credential ID
  final String? statusListCredential;

  /// Index in the status list
  final String? statusListIndex;

  const CredentialStatus({
    required this.statusType,
    this.statusListCredential,
    this.statusListIndex,
  });

  @override
  int get hashCode =>
      statusType.hashCode ^
      statusListCredential.hashCode ^
      statusListIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CredentialStatus &&
          runtimeType == other.runtimeType &&
          statusType == other.statusType &&
          statusListCredential == other.statusListCredential &&
          statusListIndex == other.statusListIndex;
}

/// Credential subject containing claims.
class CredentialSubject {
  /// Subject DID (holder)
  final String? id;

  /// All claims as JSON string (serialized HashMap<String, Value>)
  /// This avoids opaque type issues with flutter_rust_bridge
  final String claimsJson;

  const CredentialSubject({this.id, required this.claimsJson});

  @override
  int get hashCode => id.hashCode ^ claimsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CredentialSubject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          claimsJson == other.claimsJson;
}

/// ISO 18013-5 mDoc credential (Mobile Driving License, mID, etc.).
class MDocCredential {
  /// Internal identifier
  final String id;

  /// Document type (e.g., "org.iso.18013.5.1.mDL")
  final String docType;

  /// Issuing authority name
  final String issuingAuthority;

  /// Issuing country (ISO 3166-1 alpha-2)
  final String issuingCountry;

  /// Expiry date (ISO 8601)
  final String? expiryDate;

  /// Namespaced claims as JSON string (serialized HashMap<String, HashMap<String, Value>>)
  /// This avoids opaque type issues with flutter_rust_bridge
  final String namespacesJson;

  /// Trust chain verification result
  final TrustInfo? trustInfo;

  /// Portrait image (base64 encoded)
  final String? portrait;

  /// Signature image (base64 encoded)
  final String? signature;

  const MDocCredential({
    required this.id,
    required this.docType,
    required this.issuingAuthority,
    required this.issuingCountry,
    this.expiryDate,
    required this.namespacesJson,
    this.trustInfo,
    this.portrait,
    this.signature,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      docType.hashCode ^
      issuingAuthority.hashCode ^
      issuingCountry.hashCode ^
      expiryDate.hashCode ^
      namespacesJson.hashCode ^
      trustInfo.hashCode ^
      portrait.hashCode ^
      signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MDocCredential &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          docType == other.docType &&
          issuingAuthority == other.issuingAuthority &&
          issuingCountry == other.issuingCountry &&
          expiryDate == other.expiryDate &&
          namespacesJson == other.namespacesJson &&
          trustInfo == other.trustInfo &&
          portrait == other.portrait &&
          signature == other.signature;
}

/// Privacy level for credential presentation.
enum PrivacyLevel {
  /// Disclose all claims
  full,

  /// Disclose only required claims
  minimal,

  /// Custom claim selection
  custom,
}

/// Proof/signature on a credential.
class Proof {
  /// Proof type (e.g., "Ed25519Signature2020", "DataIntegrityProof")
  final String proofType;

  /// When the proof was created
  final String? created;

  /// Verification method (key reference)
  final String? verificationMethod;

  /// Purpose (e.g., "assertionMethod")
  final String? proofPurpose;

  /// The actual signature value
  final String? proofValue;

  const Proof({
    required this.proofType,
    this.created,
    this.verificationMethod,
    this.proofPurpose,
    this.proofValue,
  });

  @override
  int get hashCode =>
      proofType.hashCode ^
      created.hashCode ^
      verificationMethod.hashCode ^
      proofPurpose.hashCode ^
      proofValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Proof &&
          runtimeType == other.runtimeType &&
          proofType == other.proofType &&
          created == other.created &&
          verificationMethod == other.verificationMethod &&
          proofPurpose == other.proofPurpose &&
          proofValue == other.proofValue;
}

/// SD-JWT Verifiable Credential.
class SdJwtCredential {
  /// Unique identifier
  final String id;

  /// Credential types
  final List<String> types;

  /// Issuer identifier
  final String issuer;

  /// Issuance date
  final String issuanceDate;

  /// Expiration date
  final String? expirationDate;

  /// Disclosed claims as JSON string (serialized HashMap<String, Value>)
  /// This avoids opaque type issues with flutter_rust_bridge
  final String disclosedClaimsJson;

  /// Selectively disclosable claim names
  final List<String> disclosableClaims;

  /// Key binding JWT, if present
  final String? keyBinding;

  const SdJwtCredential({
    required this.id,
    required this.types,
    required this.issuer,
    required this.issuanceDate,
    this.expirationDate,
    required this.disclosedClaimsJson,
    required this.disclosableClaims,
    this.keyBinding,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      types.hashCode ^
      issuer.hashCode ^
      issuanceDate.hashCode ^
      expirationDate.hashCode ^
      disclosedClaimsJson.hashCode ^
      disclosableClaims.hashCode ^
      keyBinding.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SdJwtCredential &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          types == other.types &&
          issuer == other.issuer &&
          issuanceDate == other.issuanceDate &&
          expirationDate == other.expirationDate &&
          disclosedClaimsJson == other.disclosedClaimsJson &&
          disclosableClaims == other.disclosableClaims &&
          keyBinding == other.keyBinding;
}

/// Credential with selection state for presentation.
class SelectableCredential {
  /// The underlying credential
  final Credential credential;

  /// Whether this credential is selected for presentation
  final bool isSelected;

  /// Claims selected for disclosure
  final List<String> selectedClaims;

  /// Privacy level for this presentation
  final PrivacyLevel privacyLevel;

  const SelectableCredential({
    required this.credential,
    required this.isSelected,
    required this.selectedClaims,
    required this.privacyLevel,
  });

  @override
  int get hashCode =>
      credential.hashCode ^
      isSelected.hashCode ^
      selectedClaims.hashCode ^
      privacyLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectableCredential &&
          runtimeType == other.runtimeType &&
          credential == other.credential &&
          isSelected == other.isSelected &&
          selectedClaims == other.selectedClaims &&
          privacyLevel == other.privacyLevel;
}

/// Trust chain verification information.
class TrustInfo {
  /// Whether the trust chain is valid
  final bool isValid;

  /// Trust anchor used (e.g., IACA jurisdiction)
  final String? trustAnchor;

  /// Chain validation status message
  final String? statusMessage;

  /// Certificate chain (PEM encoded)
  final List<String> certificateChain;

  const TrustInfo({
    required this.isValid,
    this.trustAnchor,
    this.statusMessage,
    required this.certificateChain,
  });

  @override
  int get hashCode =>
      isValid.hashCode ^
      trustAnchor.hashCode ^
      statusMessage.hashCode ^
      certificateChain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustInfo &&
          runtimeType == other.runtimeType &&
          isValid == other.isValid &&
          trustAnchor == other.trustAnchor &&
          statusMessage == other.statusMessage &&
          certificateChain == other.certificateChain;
}

/// W3C Verifiable Credential model.
class VerifiableCredential {
  /// Unique identifier (e.g., DID URL or UUID)
  final String id;

  /// Credential types (e.g., ["VerifiableCredential", "UniversityDegreeCredential"])
  final List<String> types;

  /// Issuer DID or URL
  final String issuer;

  /// Issuer display name (resolved from metadata)
  final String? issuerName;

  /// Issuance date (ISO 8601)
  final String issuanceDate;

  /// Expiration date (ISO 8601), if any
  final String? expirationDate;

  /// Credential subject claims
  final CredentialSubject subject;

  /// Proof/signature information
  final Proof? proof;

  /// Credential status for revocation checking
  final CredentialStatus? status;

  /// Raw JSON for pass-through to platform layer
  final String? rawJson;

  const VerifiableCredential({
    required this.id,
    required this.types,
    required this.issuer,
    this.issuerName,
    required this.issuanceDate,
    this.expirationDate,
    required this.subject,
    this.proof,
    this.status,
    this.rawJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      types.hashCode ^
      issuer.hashCode ^
      issuerName.hashCode ^
      issuanceDate.hashCode ^
      expirationDate.hashCode ^
      subject.hashCode ^
      proof.hashCode ^
      status.hashCode ^
      rawJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifiableCredential &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          types == other.types &&
          issuer == other.issuer &&
          issuerName == other.issuerName &&
          issuanceDate == other.issuanceDate &&
          expirationDate == other.expirationDate &&
          subject == other.subject &&
          proof == other.proof &&
          status == other.status &&
          rawJson == other.rawJson;
}
