// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'credential.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1861125443;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'marty_authenticator_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<SelectableCredential> crateApiCreateSelectableCredential({
    required Credential credential,
    required PrivacyLevel privacyLevel,
  });

  Future<Credential> crateApiCredentialFromJson({required String json});

  Future<String> crateApiCredentialToJson({required Credential credential});

  Future<List<String>> crateApiGetCredentialClaims({
    required Credential credential,
  });

  Future<List<CredentialGroup>> crateApiGroupCredentialsByIssuer({
    required List<Credential> credentials,
  });

  Future<bool> crateApiIsCredentialExpired({required Credential credential});

  Future<MDocCredential> crateApiParseMdocCredential({
    required List<int> cborBytes,
  });

  Future<SdJwtCredential> crateApiParseSdJwtCredential({required String sdJwt});

  Future<VerifiableCredential> crateApiParseVerifiableCredential({
    required String json,
  });

  Future<MDocCredential> crateApiVerifyAndAttachTrust({
    required MDocCredential mdoc,
    required List<Uint8List> x5Chain,
  });

  Future<TrustInfo> crateApiVerifyMdocTrustChain({
    required List<Uint8List> x5Chain,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SelectableCredential> crateApiCreateSelectableCredential({
    required Credential credential,
    required PrivacyLevel privacyLevel,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_credential(credential);
          var arg1 = cst_encode_privacy_level(privacyLevel);
          return wire.wire__crate__api__create_selectable_credential(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_selectable_credential,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateSelectableCredentialConstMeta,
        argValues: [credential, privacyLevel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateSelectableCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "create_selectable_credential",
        argNames: ["credential", "privacyLevel"],
      );

  @override
  Future<Credential> crateApiCredentialFromJson({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(json);
          return wire.wire__crate__api__credential_from_json(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_credential,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiCredentialFromJsonConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialFromJsonConstMeta => const TaskConstMeta(
    debugName: "credential_from_json",
    argNames: ["json"],
  );

  @override
  Future<String> crateApiCredentialToJson({required Credential credential}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_credential(credential);
          return wire.wire__crate__api__credential_to_json(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiCredentialToJsonConstMeta,
        argValues: [credential],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialToJsonConstMeta => const TaskConstMeta(
    debugName: "credential_to_json",
    argNames: ["credential"],
  );

  @override
  Future<List<String>> crateApiGetCredentialClaims({
    required Credential credential,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_credential(credential);
          return wire.wire__crate__api__get_credential_claims(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetCredentialClaimsConstMeta,
        argValues: [credential],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetCredentialClaimsConstMeta =>
      const TaskConstMeta(
        debugName: "get_credential_claims",
        argNames: ["credential"],
      );

  @override
  Future<List<CredentialGroup>> crateApiGroupCredentialsByIssuer({
    required List<Credential> credentials,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_list_credential(credentials);
          return wire.wire__crate__api__group_credentials_by_issuer(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_credential_group,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGroupCredentialsByIssuerConstMeta,
        argValues: [credentials],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGroupCredentialsByIssuerConstMeta =>
      const TaskConstMeta(
        debugName: "group_credentials_by_issuer",
        argNames: ["credentials"],
      );

  @override
  Future<bool> crateApiIsCredentialExpired({required Credential credential}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_credential(credential);
          return wire.wire__crate__api__is_credential_expired(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsCredentialExpiredConstMeta,
        argValues: [credential],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsCredentialExpiredConstMeta =>
      const TaskConstMeta(
        debugName: "is_credential_expired",
        argNames: ["credential"],
      );

  @override
  Future<MDocCredential> crateApiParseMdocCredential({
    required List<int> cborBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_list_prim_u_8_loose(cborBytes);
          return wire.wire__crate__api__parse_mdoc_credential(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_m_doc_credential,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiParseMdocCredentialConstMeta,
        argValues: [cborBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseMdocCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "parse_mdoc_credential",
        argNames: ["cborBytes"],
      );

  @override
  Future<SdJwtCredential> crateApiParseSdJwtCredential({
    required String sdJwt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sdJwt);
          return wire.wire__crate__api__parse_sd_jwt_credential(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_sd_jwt_credential,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiParseSdJwtCredentialConstMeta,
        argValues: [sdJwt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseSdJwtCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "parse_sd_jwt_credential",
        argNames: ["sdJwt"],
      );

  @override
  Future<VerifiableCredential> crateApiParseVerifiableCredential({
    required String json,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(json);
          return wire.wire__crate__api__parse_verifiable_credential(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_verifiable_credential,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiParseVerifiableCredentialConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseVerifiableCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "parse_verifiable_credential",
        argNames: ["json"],
      );

  @override
  Future<MDocCredential> crateApiVerifyAndAttachTrust({
    required MDocCredential mdoc,
    required List<Uint8List> x5Chain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_m_doc_credential(mdoc);
          var arg1 = cst_encode_list_list_prim_u_8_strict(x5Chain);
          return wire.wire__crate__api__verify_and_attach_trust(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_m_doc_credential,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiVerifyAndAttachTrustConstMeta,
        argValues: [mdoc, x5Chain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyAndAttachTrustConstMeta =>
      const TaskConstMeta(
        debugName: "verify_and_attach_trust",
        argNames: ["mdoc", "x5Chain"],
      );

  @override
  Future<TrustInfo> crateApiVerifyMdocTrustChain({
    required List<Uint8List> x5Chain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_list_list_prim_u_8_strict(x5Chain);
          return wire.wire__crate__api__verify_mdoc_trust_chain(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_trust_info,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiVerifyMdocTrustChainConstMeta,
        argValues: [x5Chain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyMdocTrustChainConstMeta =>
      const TaskConstMeta(
        debugName: "verify_mdoc_trust_chain",
        argNames: ["x5Chain"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Credential dco_decode_box_autoadd_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_credential(raw);
  }

  @protected
  CredentialStatus dco_decode_box_autoadd_credential_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_credential_status(raw);
  }

  @protected
  MDocCredential dco_decode_box_autoadd_m_doc_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_m_doc_credential(raw);
  }

  @protected
  Proof dco_decode_box_autoadd_proof(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_proof(raw);
  }

  @protected
  SdJwtCredential dco_decode_box_autoadd_sd_jwt_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sd_jwt_credential(raw);
  }

  @protected
  TrustInfo dco_decode_box_autoadd_trust_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_trust_info(raw);
  }

  @protected
  VerifiableCredential dco_decode_box_autoadd_verifiable_credential(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_verifiable_credential(raw);
  }

  @protected
  Credential dco_decode_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Credential_VerifiableCredential(
          dco_decode_box_autoadd_verifiable_credential(raw[1]),
        );
      case 1:
        return Credential_MDoc(dco_decode_box_autoadd_m_doc_credential(raw[1]));
      case 2:
        return Credential_SdJwt(
          dco_decode_box_autoadd_sd_jwt_credential(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CredentialGroup dco_decode_credential_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CredentialGroup(
      issuer: dco_decode_String(arr[0]),
      issuerName: dco_decode_String(arr[1]),
      credentials: dco_decode_list_credential(arr[2]),
      logoUrl: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  CredentialStatus dco_decode_credential_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CredentialStatus(
      statusType: dco_decode_String(arr[0]),
      statusListCredential: dco_decode_opt_String(arr[1]),
      statusListIndex: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  CredentialSubject dco_decode_credential_subject(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CredentialSubject(
      id: dco_decode_opt_String(arr[0]),
      claimsJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Credential> dco_decode_list_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_credential).toList();
  }

  @protected
  List<CredentialGroup> dco_decode_list_credential_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_credential_group).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MDocCredential dco_decode_m_doc_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MDocCredential(
      id: dco_decode_String(arr[0]),
      docType: dco_decode_String(arr[1]),
      issuingAuthority: dco_decode_String(arr[2]),
      issuingCountry: dco_decode_String(arr[3]),
      expiryDate: dco_decode_opt_String(arr[4]),
      namespacesJson: dco_decode_String(arr[5]),
      trustInfo: dco_decode_opt_box_autoadd_trust_info(arr[6]),
      portrait: dco_decode_opt_String(arr[7]),
      signature: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CredentialStatus? dco_decode_opt_box_autoadd_credential_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_credential_status(raw);
  }

  @protected
  Proof? dco_decode_opt_box_autoadd_proof(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_proof(raw);
  }

  @protected
  TrustInfo? dco_decode_opt_box_autoadd_trust_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_trust_info(raw);
  }

  @protected
  PrivacyLevel dco_decode_privacy_level(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PrivacyLevel.values[raw as int];
  }

  @protected
  Proof dco_decode_proof(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Proof(
      proofType: dco_decode_String(arr[0]),
      created: dco_decode_opt_String(arr[1]),
      verificationMethod: dco_decode_opt_String(arr[2]),
      proofPurpose: dco_decode_opt_String(arr[3]),
      proofValue: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  SdJwtCredential dco_decode_sd_jwt_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SdJwtCredential(
      id: dco_decode_String(arr[0]),
      types: dco_decode_list_String(arr[1]),
      issuer: dco_decode_String(arr[2]),
      issuanceDate: dco_decode_String(arr[3]),
      expirationDate: dco_decode_opt_String(arr[4]),
      disclosedClaimsJson: dco_decode_String(arr[5]),
      disclosableClaims: dco_decode_list_String(arr[6]),
      keyBinding: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  SelectableCredential dco_decode_selectable_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SelectableCredential(
      credential: dco_decode_credential(arr[0]),
      isSelected: dco_decode_bool(arr[1]),
      selectedClaims: dco_decode_list_String(arr[2]),
      privacyLevel: dco_decode_privacy_level(arr[3]),
    );
  }

  @protected
  TrustInfo dco_decode_trust_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TrustInfo(
      isValid: dco_decode_bool(arr[0]),
      trustAnchor: dco_decode_opt_String(arr[1]),
      statusMessage: dco_decode_opt_String(arr[2]),
      certificateChain: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VerifiableCredential dco_decode_verifiable_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return VerifiableCredential(
      id: dco_decode_String(arr[0]),
      types: dco_decode_list_String(arr[1]),
      issuer: dco_decode_String(arr[2]),
      issuerName: dco_decode_opt_String(arr[3]),
      issuanceDate: dco_decode_String(arr[4]),
      expirationDate: dco_decode_opt_String(arr[5]),
      subject: dco_decode_credential_subject(arr[6]),
      proof: dco_decode_opt_box_autoadd_proof(arr[7]),
      status: dco_decode_opt_box_autoadd_credential_status(arr[8]),
      rawJson: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Credential sse_decode_box_autoadd_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_credential(deserializer));
  }

  @protected
  CredentialStatus sse_decode_box_autoadd_credential_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_credential_status(deserializer));
  }

  @protected
  MDocCredential sse_decode_box_autoadd_m_doc_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_m_doc_credential(deserializer));
  }

  @protected
  Proof sse_decode_box_autoadd_proof(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_proof(deserializer));
  }

  @protected
  SdJwtCredential sse_decode_box_autoadd_sd_jwt_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sd_jwt_credential(deserializer));
  }

  @protected
  TrustInfo sse_decode_box_autoadd_trust_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_trust_info(deserializer));
  }

  @protected
  VerifiableCredential sse_decode_box_autoadd_verifiable_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_verifiable_credential(deserializer));
  }

  @protected
  Credential sse_decode_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_verifiable_credential(
          deserializer,
        );
        return Credential_VerifiableCredential(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_m_doc_credential(deserializer);
        return Credential_MDoc(var_field0);
      case 2:
        var var_field0 = sse_decode_box_autoadd_sd_jwt_credential(deserializer);
        return Credential_SdJwt(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CredentialGroup sse_decode_credential_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_issuer = sse_decode_String(deserializer);
    var var_issuerName = sse_decode_String(deserializer);
    var var_credentials = sse_decode_list_credential(deserializer);
    var var_logoUrl = sse_decode_opt_String(deserializer);
    return CredentialGroup(
      issuer: var_issuer,
      issuerName: var_issuerName,
      credentials: var_credentials,
      logoUrl: var_logoUrl,
    );
  }

  @protected
  CredentialStatus sse_decode_credential_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_statusType = sse_decode_String(deserializer);
    var var_statusListCredential = sse_decode_opt_String(deserializer);
    var var_statusListIndex = sse_decode_opt_String(deserializer);
    return CredentialStatus(
      statusType: var_statusType,
      statusListCredential: var_statusListCredential,
      statusListIndex: var_statusListIndex,
    );
  }

  @protected
  CredentialSubject sse_decode_credential_subject(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_String(deserializer);
    var var_claimsJson = sse_decode_String(deserializer);
    return CredentialSubject(id: var_id, claimsJson: var_claimsJson);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Credential> sse_decode_list_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Credential>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_credential(deserializer));
    }
    return ans_;
  }

  @protected
  List<CredentialGroup> sse_decode_list_credential_group(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CredentialGroup>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_credential_group(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MDocCredential sse_decode_m_doc_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_docType = sse_decode_String(deserializer);
    var var_issuingAuthority = sse_decode_String(deserializer);
    var var_issuingCountry = sse_decode_String(deserializer);
    var var_expiryDate = sse_decode_opt_String(deserializer);
    var var_namespacesJson = sse_decode_String(deserializer);
    var var_trustInfo = sse_decode_opt_box_autoadd_trust_info(deserializer);
    var var_portrait = sse_decode_opt_String(deserializer);
    var var_signature = sse_decode_opt_String(deserializer);
    return MDocCredential(
      id: var_id,
      docType: var_docType,
      issuingAuthority: var_issuingAuthority,
      issuingCountry: var_issuingCountry,
      expiryDate: var_expiryDate,
      namespacesJson: var_namespacesJson,
      trustInfo: var_trustInfo,
      portrait: var_portrait,
      signature: var_signature,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CredentialStatus? sse_decode_opt_box_autoadd_credential_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_credential_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Proof? sse_decode_opt_box_autoadd_proof(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_proof(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TrustInfo? sse_decode_opt_box_autoadd_trust_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_trust_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PrivacyLevel sse_decode_privacy_level(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PrivacyLevel.values[inner];
  }

  @protected
  Proof sse_decode_proof(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_proofType = sse_decode_String(deserializer);
    var var_created = sse_decode_opt_String(deserializer);
    var var_verificationMethod = sse_decode_opt_String(deserializer);
    var var_proofPurpose = sse_decode_opt_String(deserializer);
    var var_proofValue = sse_decode_opt_String(deserializer);
    return Proof(
      proofType: var_proofType,
      created: var_created,
      verificationMethod: var_verificationMethod,
      proofPurpose: var_proofPurpose,
      proofValue: var_proofValue,
    );
  }

  @protected
  SdJwtCredential sse_decode_sd_jwt_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_types = sse_decode_list_String(deserializer);
    var var_issuer = sse_decode_String(deserializer);
    var var_issuanceDate = sse_decode_String(deserializer);
    var var_expirationDate = sse_decode_opt_String(deserializer);
    var var_disclosedClaimsJson = sse_decode_String(deserializer);
    var var_disclosableClaims = sse_decode_list_String(deserializer);
    var var_keyBinding = sse_decode_opt_String(deserializer);
    return SdJwtCredential(
      id: var_id,
      types: var_types,
      issuer: var_issuer,
      issuanceDate: var_issuanceDate,
      expirationDate: var_expirationDate,
      disclosedClaimsJson: var_disclosedClaimsJson,
      disclosableClaims: var_disclosableClaims,
      keyBinding: var_keyBinding,
    );
  }

  @protected
  SelectableCredential sse_decode_selectable_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_credential = sse_decode_credential(deserializer);
    var var_isSelected = sse_decode_bool(deserializer);
    var var_selectedClaims = sse_decode_list_String(deserializer);
    var var_privacyLevel = sse_decode_privacy_level(deserializer);
    return SelectableCredential(
      credential: var_credential,
      isSelected: var_isSelected,
      selectedClaims: var_selectedClaims,
      privacyLevel: var_privacyLevel,
    );
  }

  @protected
  TrustInfo sse_decode_trust_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isValid = sse_decode_bool(deserializer);
    var var_trustAnchor = sse_decode_opt_String(deserializer);
    var var_statusMessage = sse_decode_opt_String(deserializer);
    var var_certificateChain = sse_decode_list_String(deserializer);
    return TrustInfo(
      isValid: var_isValid,
      trustAnchor: var_trustAnchor,
      statusMessage: var_statusMessage,
      certificateChain: var_certificateChain,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VerifiableCredential sse_decode_verifiable_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_types = sse_decode_list_String(deserializer);
    var var_issuer = sse_decode_String(deserializer);
    var var_issuerName = sse_decode_opt_String(deserializer);
    var var_issuanceDate = sse_decode_String(deserializer);
    var var_expirationDate = sse_decode_opt_String(deserializer);
    var var_subject = sse_decode_credential_subject(deserializer);
    var var_proof = sse_decode_opt_box_autoadd_proof(deserializer);
    var var_status = sse_decode_opt_box_autoadd_credential_status(deserializer);
    var var_rawJson = sse_decode_opt_String(deserializer);
    return VerifiableCredential(
      id: var_id,
      types: var_types,
      issuer: var_issuer,
      issuerName: var_issuerName,
      issuanceDate: var_issuanceDate,
      expirationDate: var_expirationDate,
      subject: var_subject,
      proof: var_proof,
      status: var_status,
      rawJson: var_rawJson,
    );
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_privacy_level(PrivacyLevel raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_credential(
    Credential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_credential(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_credential_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_m_doc_credential(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_proof(Proof self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_proof(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sd_jwt_credential(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_trust_info(
    TrustInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_trust_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_verifiable_credential(self, serializer);
  }

  @protected
  void sse_encode_credential(Credential self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Credential_VerifiableCredential(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_verifiable_credential(field0, serializer);
      case Credential_MDoc(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_m_doc_credential(field0, serializer);
      case Credential_SdJwt(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_sd_jwt_credential(field0, serializer);
    }
  }

  @protected
  void sse_encode_credential_group(
    CredentialGroup self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.issuer, serializer);
    sse_encode_String(self.issuerName, serializer);
    sse_encode_list_credential(self.credentials, serializer);
    sse_encode_opt_String(self.logoUrl, serializer);
  }

  @protected
  void sse_encode_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.statusType, serializer);
    sse_encode_opt_String(self.statusListCredential, serializer);
    sse_encode_opt_String(self.statusListIndex, serializer);
  }

  @protected
  void sse_encode_credential_subject(
    CredentialSubject self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.id, serializer);
    sse_encode_String(self.claimsJson, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_credential(
    List<Credential> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_credential(item, serializer);
    }
  }

  @protected
  void sse_encode_list_credential_group(
    List<CredentialGroup> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_credential_group(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.docType, serializer);
    sse_encode_String(self.issuingAuthority, serializer);
    sse_encode_String(self.issuingCountry, serializer);
    sse_encode_opt_String(self.expiryDate, serializer);
    sse_encode_String(self.namespacesJson, serializer);
    sse_encode_opt_box_autoadd_trust_info(self.trustInfo, serializer);
    sse_encode_opt_String(self.portrait, serializer);
    sse_encode_opt_String(self.signature, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_credential_status(
    CredentialStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_credential_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_proof(Proof? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_proof(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_trust_info(
    TrustInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_trust_info(self, serializer);
    }
  }

  @protected
  void sse_encode_privacy_level(PrivacyLevel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_proof(Proof self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.proofType, serializer);
    sse_encode_opt_String(self.created, serializer);
    sse_encode_opt_String(self.verificationMethod, serializer);
    sse_encode_opt_String(self.proofPurpose, serializer);
    sse_encode_opt_String(self.proofValue, serializer);
  }

  @protected
  void sse_encode_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_list_String(self.types, serializer);
    sse_encode_String(self.issuer, serializer);
    sse_encode_String(self.issuanceDate, serializer);
    sse_encode_opt_String(self.expirationDate, serializer);
    sse_encode_String(self.disclosedClaimsJson, serializer);
    sse_encode_list_String(self.disclosableClaims, serializer);
    sse_encode_opt_String(self.keyBinding, serializer);
  }

  @protected
  void sse_encode_selectable_credential(
    SelectableCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_credential(self.credential, serializer);
    sse_encode_bool(self.isSelected, serializer);
    sse_encode_list_String(self.selectedClaims, serializer);
    sse_encode_privacy_level(self.privacyLevel, serializer);
  }

  @protected
  void sse_encode_trust_info(TrustInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isValid, serializer);
    sse_encode_opt_String(self.trustAnchor, serializer);
    sse_encode_opt_String(self.statusMessage, serializer);
    sse_encode_list_String(self.certificateChain, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_list_String(self.types, serializer);
    sse_encode_String(self.issuer, serializer);
    sse_encode_opt_String(self.issuerName, serializer);
    sse_encode_String(self.issuanceDate, serializer);
    sse_encode_opt_String(self.expirationDate, serializer);
    sse_encode_credential_subject(self.subject, serializer);
    sse_encode_opt_box_autoadd_proof(self.proof, serializer);
    sse_encode_opt_box_autoadd_credential_status(self.status, serializer);
    sse_encode_opt_String(self.rawJson, serializer);
  }
}
