// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'biometrics.dart';
import 'credential.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PresentationPolicyPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  PresentationPolicy
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    dynamic raw,
  );

  @protected
  PresentationPolicy
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Credential dco_decode_box_autoadd_credential(dynamic raw);

  @protected
  CredentialStatus dco_decode_box_autoadd_credential_status(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  MDocCredential dco_decode_box_autoadd_m_doc_credential(dynamic raw);

  @protected
  Proof dco_decode_box_autoadd_proof(dynamic raw);

  @protected
  SdJwtCredential dco_decode_box_autoadd_sd_jwt_credential(dynamic raw);

  @protected
  TrustInfo dco_decode_box_autoadd_trust_info(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  VerifiableCredential dco_decode_box_autoadd_verifiable_credential(
    dynamic raw,
  );

  @protected
  Credential dco_decode_credential(dynamic raw);

  @protected
  CredentialGroup dco_decode_credential_group(dynamic raw);

  @protected
  CredentialStatus dco_decode_credential_status(dynamic raw);

  @protected
  CredentialSubject dco_decode_credential_subject(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FrbAgeEstimate dco_decode_frb_age_estimate(dynamic raw);

  @protected
  FrbAuthorizationRequest dco_decode_frb_authorization_request(dynamic raw);

  @protected
  FrbCredentialOffer dco_decode_frb_credential_offer(dynamic raw);

  @protected
  FrbCredentialResponse dco_decode_frb_credential_response(dynamic raw);

  @protected
  FrbFaceMatchResult dco_decode_frb_face_match_result(dynamic raw);

  @protected
  FrbFaceQuality dco_decode_frb_face_quality(dynamic raw);

  @protected
  FrbIssuerMetadata dco_decode_frb_issuer_metadata(dynamic raw);

  @protected
  FrbPresentationRequest dco_decode_frb_presentation_request(dynamic raw);

  @protected
  FrbPresentationResponse dco_decode_frb_presentation_response(dynamic raw);

  @protected
  FrbTokenResponse dco_decode_frb_token_response(dynamic raw);

  @protected
  FrbZkProofEntry dco_decode_frb_zk_proof_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IssuerCheckResultOutput dco_decode_issuer_check_result_output(dynamic raw);

  @protected
  List<PresentationPolicy>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Credential> dco_decode_list_credential(dynamic raw);

  @protected
  List<CredentialGroup> dco_decode_list_credential_group(dynamic raw);

  @protected
  List<FrbZkProofEntry> dco_decode_list_frb_zk_proof_entry(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RankableCredentialInput> dco_decode_list_rankable_credential_input(
    dynamic raw,
  );

  @protected
  MDocCredential dco_decode_m_doc_credential(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CredentialStatus? dco_decode_opt_box_autoadd_credential_status(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  Proof? dco_decode_opt_box_autoadd_proof(dynamic raw);

  @protected
  TrustInfo? dco_decode_opt_box_autoadd_trust_info(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PolicyEvaluationResult dco_decode_policy_evaluation_result(dynamic raw);

  @protected
  PrivacyLevel dco_decode_privacy_level(dynamic raw);

  @protected
  Proof dco_decode_proof(dynamic raw);

  @protected
  RankableCredentialInput dco_decode_rankable_credential_input(dynamic raw);

  @protected
  SdJwtCredential dco_decode_sd_jwt_credential(dynamic raw);

  @protected
  SelectableCredential dco_decode_selectable_credential(dynamic raw);

  @protected
  TrustInfo dco_decode_trust_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VerifiableCredential dco_decode_verifiable_credential(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  PresentationPolicy
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    SseDeserializer deserializer,
  );

  @protected
  PresentationPolicy
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Credential sse_decode_box_autoadd_credential(SseDeserializer deserializer);

  @protected
  CredentialStatus sse_decode_box_autoadd_credential_status(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  MDocCredential sse_decode_box_autoadd_m_doc_credential(
    SseDeserializer deserializer,
  );

  @protected
  Proof sse_decode_box_autoadd_proof(SseDeserializer deserializer);

  @protected
  SdJwtCredential sse_decode_box_autoadd_sd_jwt_credential(
    SseDeserializer deserializer,
  );

  @protected
  TrustInfo sse_decode_box_autoadd_trust_info(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  VerifiableCredential sse_decode_box_autoadd_verifiable_credential(
    SseDeserializer deserializer,
  );

  @protected
  Credential sse_decode_credential(SseDeserializer deserializer);

  @protected
  CredentialGroup sse_decode_credential_group(SseDeserializer deserializer);

  @protected
  CredentialStatus sse_decode_credential_status(SseDeserializer deserializer);

  @protected
  CredentialSubject sse_decode_credential_subject(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FrbAgeEstimate sse_decode_frb_age_estimate(SseDeserializer deserializer);

  @protected
  FrbAuthorizationRequest sse_decode_frb_authorization_request(
    SseDeserializer deserializer,
  );

  @protected
  FrbCredentialOffer sse_decode_frb_credential_offer(
    SseDeserializer deserializer,
  );

  @protected
  FrbCredentialResponse sse_decode_frb_credential_response(
    SseDeserializer deserializer,
  );

  @protected
  FrbFaceMatchResult sse_decode_frb_face_match_result(
    SseDeserializer deserializer,
  );

  @protected
  FrbFaceQuality sse_decode_frb_face_quality(SseDeserializer deserializer);

  @protected
  FrbIssuerMetadata sse_decode_frb_issuer_metadata(
    SseDeserializer deserializer,
  );

  @protected
  FrbPresentationRequest sse_decode_frb_presentation_request(
    SseDeserializer deserializer,
  );

  @protected
  FrbPresentationResponse sse_decode_frb_presentation_response(
    SseDeserializer deserializer,
  );

  @protected
  FrbTokenResponse sse_decode_frb_token_response(SseDeserializer deserializer);

  @protected
  FrbZkProofEntry sse_decode_frb_zk_proof_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IssuerCheckResultOutput sse_decode_issuer_check_result_output(
    SseDeserializer deserializer,
  );

  @protected
  List<PresentationPolicy>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Credential> sse_decode_list_credential(SseDeserializer deserializer);

  @protected
  List<CredentialGroup> sse_decode_list_credential_group(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbZkProofEntry> sse_decode_list_frb_zk_proof_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RankableCredentialInput> sse_decode_list_rankable_credential_input(
    SseDeserializer deserializer,
  );

  @protected
  MDocCredential sse_decode_m_doc_credential(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CredentialStatus? sse_decode_opt_box_autoadd_credential_status(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  Proof? sse_decode_opt_box_autoadd_proof(SseDeserializer deserializer);

  @protected
  TrustInfo? sse_decode_opt_box_autoadd_trust_info(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PolicyEvaluationResult sse_decode_policy_evaluation_result(
    SseDeserializer deserializer,
  );

  @protected
  PrivacyLevel sse_decode_privacy_level(SseDeserializer deserializer);

  @protected
  Proof sse_decode_proof(SseDeserializer deserializer);

  @protected
  RankableCredentialInput sse_decode_rankable_credential_input(
    SseDeserializer deserializer,
  );

  @protected
  SdJwtCredential sse_decode_sd_jwt_credential(SseDeserializer deserializer);

  @protected
  SelectableCredential sse_decode_selectable_credential(
    SseDeserializer deserializer,
  );

  @protected
  TrustInfo sse_decode_trust_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VerifiableCredential sse_decode_verifiable_credential(
    SseDeserializer deserializer,
  );

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_credential(Credential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_credential(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_credential_status(CredentialStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_credential_status(raw);
  }

  @protected
  double cst_encode_box_autoadd_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_f_32(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_m_doc_credential(MDocCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_m_doc_credential(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_proof(Proof raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_proof(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_sd_jwt_credential(SdJwtCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_sd_jwt_credential(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_trust_info(TrustInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_trust_info(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_verifiable_credential(VerifiableCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_verifiable_credential(raw);
  }

  @protected
  JSAny cst_encode_credential(Credential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is Credential_VerifiableCredential) {
      return [
        0,
        cst_encode_box_autoadd_verifiable_credential(raw.field0),
      ].jsify()!;
    }
    if (raw is Credential_MDoc) {
      return [1, cst_encode_box_autoadd_m_doc_credential(raw.field0)].jsify()!;
    }
    if (raw is Credential_SdJwt) {
      return [2, cst_encode_box_autoadd_sd_jwt_credential(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_credential_group(CredentialGroup raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.issuer),
      cst_encode_String(raw.issuerName),
      cst_encode_list_credential(raw.credentials),
      cst_encode_opt_String(raw.logoUrl),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_credential_status(CredentialStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.statusType),
      cst_encode_opt_String(raw.statusListCredential),
      cst_encode_opt_String(raw.statusListIndex),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_credential_subject(CredentialSubject raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.id),
      cst_encode_String(raw.claimsJson),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_age_estimate(FrbAgeEstimate raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_8(raw.estimatedAge),
      cst_encode_f_32(raw.confidence),
      cst_encode_u_8(raw.ageRangeLow),
      cst_encode_u_8(raw.ageRangeHigh),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_authorization_request(FrbAuthorizationRequest raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.authorizationUrl),
      cst_encode_String(raw.codeVerifier),
      cst_encode_String(raw.state),
      cst_encode_String(raw.redirectUri),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_credential_offer(FrbCredentialOffer raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.credentialIssuer),
      cst_encode_list_String(raw.credentialConfigurationIds),
      cst_encode_opt_String(raw.preAuthorizedCode),
      cst_encode_bool(raw.txCodeRequired),
      cst_encode_opt_String(raw.issuerState),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_credential_response(FrbCredentialResponse raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.format),
      cst_encode_opt_String(raw.credential),
      cst_encode_opt_String(raw.transactionId),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_face_match_result(FrbFaceMatchResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.verified),
      cst_encode_f_32(raw.similarity),
      cst_encode_f_32(raw.threshold),
      cst_encode_String(raw.provider),
      cst_encode_opt_box_autoadd_f_32(raw.referenceQuality),
      cst_encode_opt_box_autoadd_f_32(raw.probeQuality),
      cst_encode_u_64(raw.processingTimeMs),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_face_quality(FrbFaceQuality raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_f_32(raw.overallScore),
      cst_encode_bool(raw.faceDetected),
      cst_encode_u_32(raw.faceCount),
      cst_encode_f_32(raw.sharpness),
      cst_encode_f_32(raw.brightness),
      cst_encode_f_32(raw.contrast),
      cst_encode_f_32(raw.faceSize),
      cst_encode_f_32(raw.pose),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_issuer_metadata(FrbIssuerMetadata raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.credentialIssuer),
      cst_encode_String(raw.tokenEndpoint),
      cst_encode_String(raw.credentialEndpoint),
      cst_encode_opt_String(raw.authorizationEndpoint),
      cst_encode_list_String(raw.grantTypesSupported),
      cst_encode_String(raw.credentialConfigurationsJson),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_presentation_request(FrbPresentationRequest raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.clientId),
      cst_encode_String(raw.nonce),
      cst_encode_String(raw.responseUri),
      cst_encode_String(raw.queryType),
      cst_encode_opt_String(raw.presentationDefinitionJson),
      cst_encode_opt_String(raw.dcqlQueryJson),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_presentation_response(FrbPresentationResponse raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.ok),
      cst_encode_opt_String(raw.redirectUri),
      cst_encode_opt_String(raw.error),
      cst_encode_opt_String(raw.errorDescription),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_token_response(FrbTokenResponse raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.accessToken),
      cst_encode_String(raw.tokenType),
      cst_encode_opt_box_autoadd_u_64(raw.expiresIn),
      cst_encode_opt_String(raw.scope),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_frb_zk_proof_entry(FrbZkProofEntry raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.descriptorId),
      cst_encode_String(raw.predicateId),
      cst_encode_list_prim_u_8_strict(raw.proofBytes),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_issuer_check_result_output(IssuerCheckResultOutput raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.isTrusted),
      cst_encode_opt_String(raw.violationMessage),
    ].jsify()!;
  }

  @protected
  JSAny
  cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    List<PresentationPolicy> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(
          cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy,
        )
        .toList()
        .jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_credential(List<Credential> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_credential).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_credential_group(List<CredentialGroup> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_credential_group).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_frb_zk_proof_entry(List<FrbZkProofEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_frb_zk_proof_entry).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_list_prim_u_8_strict).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_rankable_credential_input(
    List<RankableCredentialInput> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_rankable_credential_input).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_m_doc_credential(MDocCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.docType),
      cst_encode_String(raw.issuingAuthority),
      cst_encode_String(raw.issuingCountry),
      cst_encode_opt_String(raw.expiryDate),
      cst_encode_String(raw.namespacesJson),
      cst_encode_opt_box_autoadd_trust_info(raw.trustInfo),
      cst_encode_opt_String(raw.portrait),
      cst_encode_opt_String(raw.signature),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_credential_status(CredentialStatus? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_credential_status(raw);
  }

  @protected
  double? cst_encode_opt_box_autoadd_f_32(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_f_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_proof(Proof? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_proof(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_trust_info(TrustInfo? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_trust_info(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  JSAny cst_encode_policy_evaluation_result(PolicyEvaluationResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.isSatisfied),
      cst_encode_list_String(raw.minimumDisclosureClaims),
      cst_encode_list_String(raw.missingRequiredClaims),
      cst_encode_String(raw.policyId),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_proof(Proof raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.proofType),
      cst_encode_opt_String(raw.created),
      cst_encode_opt_String(raw.verificationMethod),
      cst_encode_opt_String(raw.proofPurpose),
      cst_encode_opt_String(raw.proofValue),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_rankable_credential_input(RankableCredentialInput raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.credentialId),
      cst_encode_String(raw.issuerId),
      cst_encode_i_64(raw.issuedAtUnix),
      cst_encode_f_64(raw.trustLevel),
      cst_encode_usize(raw.claimCount),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sd_jwt_credential(SdJwtCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_list_String(raw.types),
      cst_encode_String(raw.issuer),
      cst_encode_String(raw.issuanceDate),
      cst_encode_opt_String(raw.expirationDate),
      cst_encode_String(raw.disclosedClaimsJson),
      cst_encode_list_String(raw.disclosableClaims),
      cst_encode_opt_String(raw.keyBinding),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_selectable_credential(SelectableCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_credential(raw.credential),
      cst_encode_bool(raw.isSelected),
      cst_encode_list_String(raw.selectedClaims),
      cst_encode_privacy_level(raw.privacyLevel),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_trust_info(TrustInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.isValid),
      cst_encode_opt_String(raw.trustAnchor),
      cst_encode_opt_String(raw.statusMessage),
      cst_encode_list_String(raw.certificateChain),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_verifiable_credential(VerifiableCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_list_String(raw.types),
      cst_encode_String(raw.issuer),
      cst_encode_opt_String(raw.issuerName),
      cst_encode_String(raw.issuanceDate),
      cst_encode_opt_String(raw.expirationDate),
      cst_encode_credential_subject(raw.subject),
      cst_encode_opt_box_autoadd_proof(raw.proof),
      cst_encode_opt_box_autoadd_credential_status(raw.status),
      cst_encode_opt_String(raw.rawJson),
    ].jsify()!;
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    PresentationPolicy raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    PresentationPolicy raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_privacy_level(PrivacyLevel raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    PresentationPolicy self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    PresentationPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_credential(
    Credential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proof(Proof self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trust_info(
    TrustInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential(Credential self, SseSerializer serializer);

  @protected
  void sse_encode_credential_group(
    CredentialGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential_subject(
    CredentialSubject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_frb_age_estimate(
    FrbAgeEstimate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_authorization_request(
    FrbAuthorizationRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_credential_offer(
    FrbCredentialOffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_credential_response(
    FrbCredentialResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_face_match_result(
    FrbFaceMatchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_face_quality(
    FrbFaceQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_issuer_metadata(
    FrbIssuerMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_presentation_request(
    FrbPresentationRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_presentation_response(
    FrbPresentationResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_token_response(
    FrbTokenResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_zk_proof_entry(
    FrbZkProofEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_issuer_check_result_output(
    IssuerCheckResultOutput self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    List<PresentationPolicy> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_credential(
    List<Credential> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_credential_group(
    List<CredentialGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_zk_proof_entry(
    List<FrbZkProofEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rankable_credential_input(
    List<RankableCredentialInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_credential_status(
    CredentialStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_proof(Proof? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_trust_info(
    TrustInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_policy_evaluation_result(
    PolicyEvaluationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_privacy_level(PrivacyLevel self, SseSerializer serializer);

  @protected
  void sse_encode_proof(Proof self, SseSerializer serializer);

  @protected
  void sse_encode_rankable_credential_input(
    RankableCredentialInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_selectable_credential(
    SelectableCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trust_info(TrustInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__biometrics__assess_face_quality(
    NativePortType port_,
    String image,
    String? models_dir,
  ) => wasmModule.wire__crate__biometrics__assess_face_quality(
    port_,
    image,
    models_dir,
  );

  void wire__crate__api__check_issuer_constraints(
    NativePortType port_,
    String policy_json,
    String issuer_id,
    bool trust_profile_verified,
  ) => wasmModule.wire__crate__api__check_issuer_constraints(
    port_,
    policy_json,
    issuer_id,
    trust_profile_verified,
  );

  void wire__crate__api__create_selectable_credential(
    NativePortType port_,
    JSAny credential,
    int privacy_level,
  ) => wasmModule.wire__crate__api__create_selectable_credential(
    port_,
    credential,
    privacy_level,
  );

  void wire__crate__api__credential_from_json(
    NativePortType port_,
    String json,
  ) => wasmModule.wire__crate__api__credential_from_json(port_, json);

  void wire__crate__api__credential_to_json(
    NativePortType port_,
    JSAny credential,
  ) => wasmModule.wire__crate__api__credential_to_json(port_, credential);

  void wire__crate__biometrics__estimate_face_age(
    NativePortType port_,
    String image,
    String? models_dir,
  ) => wasmModule.wire__crate__biometrics__estimate_face_age(
    port_,
    image,
    models_dir,
  );

  void wire__crate__api__evaluate_presentation_request(
    NativePortType port_,
    String request_json,
    JSAny policies_json,
    JSAny credentials,
  ) => wasmModule.wire__crate__api__evaluate_presentation_request(
    port_,
    request_json,
    policies_json,
    credentials,
  );

  void wire__crate__api__get_credential_claims(
    NativePortType port_,
    JSAny credential,
  ) => wasmModule.wire__crate__api__get_credential_claims(port_, credential);

  void wire__crate__api__get_minimum_disclosure_set(
    NativePortType port_,
    String policy_json,
    JSAny credential,
  ) => wasmModule.wire__crate__api__get_minimum_disclosure_set(
    port_,
    policy_json,
    credential,
  );

  void wire__crate__api__group_credentials_by_issuer(
    NativePortType port_,
    JSAny credentials,
  ) => wasmModule.wire__crate__api__group_credentials_by_issuer(
    port_,
    credentials,
  );

  void wire__crate__api__is_credential_expired(
    NativePortType port_,
    JSAny credential,
  ) => wasmModule.wire__crate__api__is_credential_expired(port_, credential);

  void wire__crate__api__parse_mdoc_credential(
    NativePortType port_,
    JSAny cbor_bytes,
  ) => wasmModule.wire__crate__api__parse_mdoc_credential(port_, cbor_bytes);

  void wire__crate__api__parse_sd_jwt_credential(
    NativePortType port_,
    String sd_jwt,
  ) => wasmModule.wire__crate__api__parse_sd_jwt_credential(port_, sd_jwt);

  void wire__crate__api__parse_verifiable_credential(
    NativePortType port_,
    String json,
  ) => wasmModule.wire__crate__api__parse_verifiable_credential(port_, json);

  void wire__crate__api__rank_matching_credentials(
    NativePortType port_,
    String policy_json,
    JSAny credentials,
  ) => wasmModule.wire__crate__api__rank_matching_credentials(
    port_,
    policy_json,
    credentials,
  );

  void wire__crate__api__sync_policies(
    NativePortType port_,
    String license_jwt,
    String endpoint,
  ) => wasmModule.wire__crate__api__sync_policies(port_, license_jwt, endpoint);

  void wire__crate__api__verify_and_attach_trust(
    NativePortType port_,
    JSAny mdoc,
    JSAny x5chain,
  ) => wasmModule.wire__crate__api__verify_and_attach_trust(
    port_,
    mdoc,
    x5chain,
  );

  void wire__crate__biometrics__verify_face_match(
    NativePortType port_,
    String reference_image,
    String probe_image,
    double? threshold,
    String? models_dir,
  ) => wasmModule.wire__crate__biometrics__verify_face_match(
    port_,
    reference_image,
    probe_image,
    threshold,
    models_dir,
  );

  void wire__crate__api__verify_mdoc_trust_chain(
    NativePortType port_,
    JSAny x5chain,
  ) => wasmModule.wire__crate__api__verify_mdoc_trust_chain(port_, x5chain);

  void wire__crate__api__wallet_build_and_submit_presentation(
    NativePortType port_,
    String response_uri,
    String? presentation_definition_json,
    String? dcql_query_json,
    String credentials_json,
  ) => wasmModule.wire__crate__api__wallet_build_and_submit_presentation(
    port_,
    response_uri,
    presentation_definition_json,
    dcql_query_json,
    credentials_json,
  );

  void wire__crate__api__wallet_build_and_submit_zk_presentation(
    NativePortType port_,
    String response_uri,
    String presentation_definition_json,
    String credentials_json,
    JSAny zk_proofs,
  ) => wasmModule.wire__crate__api__wallet_build_and_submit_zk_presentation(
    port_,
    response_uri,
    presentation_definition_json,
    credentials_json,
    zk_proofs,
  );

  void wire__crate__api__wallet_build_auth_request(
    NativePortType port_,
    String issuer_metadata_json,
    String credential_configuration_id,
    String client_id,
    String redirect_uri,
    String? issuer_state,
  ) => wasmModule.wire__crate__api__wallet_build_auth_request(
    port_,
    issuer_metadata_json,
    credential_configuration_id,
    client_id,
    redirect_uri,
    issuer_state,
  );

  void wire__crate__api__wallet_create_proof_jwt(
    NativePortType port_,
    String holder_kid,
    String c_nonce,
    String issuer_url,
    String jwk_json,
  ) => wasmModule.wire__crate__api__wallet_create_proof_jwt(
    port_,
    holder_kid,
    c_nonce,
    issuer_url,
    jwk_json,
  );

  void wire__crate__api__wallet_exchange_auth_code_token(
    NativePortType port_,
    String token_endpoint,
    String code,
    String code_verifier,
    String? redirect_uri,
    String? client_id,
  ) => wasmModule.wire__crate__api__wallet_exchange_auth_code_token(
    port_,
    token_endpoint,
    code,
    code_verifier,
    redirect_uri,
    client_id,
  );

  void wire__crate__api__wallet_exchange_pre_auth_token(
    NativePortType port_,
    String token_endpoint,
    String pre_auth_code,
    String? tx_code,
  ) => wasmModule.wire__crate__api__wallet_exchange_pre_auth_token(
    port_,
    token_endpoint,
    pre_auth_code,
    tx_code,
  );

  void wire__crate__api__wallet_fetch_issuer_metadata(
    NativePortType port_,
    String issuer_url,
  ) => wasmModule.wire__crate__api__wallet_fetch_issuer_metadata(
    port_,
    issuer_url,
  );

  void wire__crate__api__wallet_parse_credential_offer(
    NativePortType port_,
    String offer_uri,
  ) => wasmModule.wire__crate__api__wallet_parse_credential_offer(
    port_,
    offer_uri,
  );

  void wire__crate__api__wallet_parse_presentation_request(
    NativePortType port_,
    String request_uri,
  ) => wasmModule.wire__crate__api__wallet_parse_presentation_request(
    port_,
    request_uri,
  );

  void wire__crate__api__wallet_request_credential(
    NativePortType port_,
    String credential_endpoint,
    String access_token,
    String credential_format,
    String? credential_configuration_id,
    String proof_jwt,
  ) => wasmModule.wire__crate__api__wallet_request_credential(
    port_,
    credential_endpoint,
    access_token,
    credential_format,
    credential_configuration_id,
    proof_jwt,
  );

  void wire__crate__api__zk_is_supported_on_device(NativePortType port_) =>
      wasmModule.wire__crate__api__zk_is_supported_on_device(port_);

  void wire__crate__api__zk_prove(
    NativePortType port_,
    String predicate_id,
    String claim_value,
    JSAny mdoc_bytes,
    String issuer_pkx,
    String issuer_pky,
    String doc_type,
    JSAny session_nonce,
  ) => wasmModule.wire__crate__api__zk_prove(
    port_,
    predicate_id,
    claim_value,
    mdoc_bytes,
    issuer_pkx,
    issuer_pky,
    doc_type,
    session_nonce,
  );

  void wire__crate__api__zk_prove_from_presentation_definition(
    NativePortType port_,
    String presentation_definition_json,
    JSAny mdoc_bytes,
    String issuer_pkx,
    String issuer_pky,
    String doc_type,
    String secrets_json,
    JSAny session_nonce,
  ) => wasmModule.wire__crate__api__zk_prove_from_presentation_definition(
    port_,
    presentation_definition_json,
    mdoc_bytes,
    issuer_pkx,
    issuer_pky,
    doc_type,
    secrets_json,
    session_nonce,
  );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__biometrics__assess_face_quality(
    NativePortType port_,
    String image,
    String? models_dir,
  );

  external void wire__crate__api__check_issuer_constraints(
    NativePortType port_,
    String policy_json,
    String issuer_id,
    bool trust_profile_verified,
  );

  external void wire__crate__api__create_selectable_credential(
    NativePortType port_,
    JSAny credential,
    int privacy_level,
  );

  external void wire__crate__api__credential_from_json(
    NativePortType port_,
    String json,
  );

  external void wire__crate__api__credential_to_json(
    NativePortType port_,
    JSAny credential,
  );

  external void wire__crate__biometrics__estimate_face_age(
    NativePortType port_,
    String image,
    String? models_dir,
  );

  external void wire__crate__api__evaluate_presentation_request(
    NativePortType port_,
    String request_json,
    JSAny policies_json,
    JSAny credentials,
  );

  external void wire__crate__api__get_credential_claims(
    NativePortType port_,
    JSAny credential,
  );

  external void wire__crate__api__get_minimum_disclosure_set(
    NativePortType port_,
    String policy_json,
    JSAny credential,
  );

  external void wire__crate__api__group_credentials_by_issuer(
    NativePortType port_,
    JSAny credentials,
  );

  external void wire__crate__api__is_credential_expired(
    NativePortType port_,
    JSAny credential,
  );

  external void wire__crate__api__parse_mdoc_credential(
    NativePortType port_,
    JSAny cbor_bytes,
  );

  external void wire__crate__api__parse_sd_jwt_credential(
    NativePortType port_,
    String sd_jwt,
  );

  external void wire__crate__api__parse_verifiable_credential(
    NativePortType port_,
    String json,
  );

  external void wire__crate__api__rank_matching_credentials(
    NativePortType port_,
    String policy_json,
    JSAny credentials,
  );

  external void wire__crate__api__sync_policies(
    NativePortType port_,
    String license_jwt,
    String endpoint,
  );

  external void wire__crate__api__verify_and_attach_trust(
    NativePortType port_,
    JSAny mdoc,
    JSAny x5chain,
  );

  external void wire__crate__biometrics__verify_face_match(
    NativePortType port_,
    String reference_image,
    String probe_image,
    double? threshold,
    String? models_dir,
  );

  external void wire__crate__api__verify_mdoc_trust_chain(
    NativePortType port_,
    JSAny x5chain,
  );

  external void wire__crate__api__wallet_build_and_submit_presentation(
    NativePortType port_,
    String response_uri,
    String? presentation_definition_json,
    String? dcql_query_json,
    String credentials_json,
  );

  external void wire__crate__api__wallet_build_and_submit_zk_presentation(
    NativePortType port_,
    String response_uri,
    String presentation_definition_json,
    String credentials_json,
    JSAny zk_proofs,
  );

  external void wire__crate__api__wallet_build_auth_request(
    NativePortType port_,
    String issuer_metadata_json,
    String credential_configuration_id,
    String client_id,
    String redirect_uri,
    String? issuer_state,
  );

  external void wire__crate__api__wallet_create_proof_jwt(
    NativePortType port_,
    String holder_kid,
    String c_nonce,
    String issuer_url,
    String jwk_json,
  );

  external void wire__crate__api__wallet_exchange_auth_code_token(
    NativePortType port_,
    String token_endpoint,
    String code,
    String code_verifier,
    String? redirect_uri,
    String? client_id,
  );

  external void wire__crate__api__wallet_exchange_pre_auth_token(
    NativePortType port_,
    String token_endpoint,
    String pre_auth_code,
    String? tx_code,
  );

  external void wire__crate__api__wallet_fetch_issuer_metadata(
    NativePortType port_,
    String issuer_url,
  );

  external void wire__crate__api__wallet_parse_credential_offer(
    NativePortType port_,
    String offer_uri,
  );

  external void wire__crate__api__wallet_parse_presentation_request(
    NativePortType port_,
    String request_uri,
  );

  external void wire__crate__api__wallet_request_credential(
    NativePortType port_,
    String credential_endpoint,
    String access_token,
    String credential_format,
    String? credential_configuration_id,
    String proof_jwt,
  );

  external void wire__crate__api__zk_is_supported_on_device(
    NativePortType port_,
  );

  external void wire__crate__api__zk_prove(
    NativePortType port_,
    String predicate_id,
    String claim_value,
    JSAny mdoc_bytes,
    String issuer_pkx,
    String issuer_pky,
    String doc_type,
    JSAny session_nonce,
  );

  external void wire__crate__api__zk_prove_from_presentation_definition(
    NativePortType port_,
    String presentation_definition_json,
    JSAny mdoc_bytes,
    String issuer_pkx,
    String issuer_pky,
    String doc_type,
    String secrets_json,
    JSAny session_nonce,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPresentationPolicy(
    int ptr,
  );
}
