// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'credential.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Credential dco_decode_box_autoadd_credential(dynamic raw);

  @protected
  CredentialStatus dco_decode_box_autoadd_credential_status(dynamic raw);

  @protected
  MDocCredential dco_decode_box_autoadd_m_doc_credential(dynamic raw);

  @protected
  Proof dco_decode_box_autoadd_proof(dynamic raw);

  @protected
  SdJwtCredential dco_decode_box_autoadd_sd_jwt_credential(dynamic raw);

  @protected
  TrustInfo dco_decode_box_autoadd_trust_info(dynamic raw);

  @protected
  VerifiableCredential dco_decode_box_autoadd_verifiable_credential(
    dynamic raw,
  );

  @protected
  Credential dco_decode_credential(dynamic raw);

  @protected
  CredentialGroup dco_decode_credential_group(dynamic raw);

  @protected
  CredentialStatus dco_decode_credential_status(dynamic raw);

  @protected
  CredentialSubject dco_decode_credential_subject(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Credential> dco_decode_list_credential(dynamic raw);

  @protected
  List<CredentialGroup> dco_decode_list_credential_group(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MDocCredential dco_decode_m_doc_credential(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CredentialStatus? dco_decode_opt_box_autoadd_credential_status(dynamic raw);

  @protected
  Proof? dco_decode_opt_box_autoadd_proof(dynamic raw);

  @protected
  TrustInfo? dco_decode_opt_box_autoadd_trust_info(dynamic raw);

  @protected
  PrivacyLevel dco_decode_privacy_level(dynamic raw);

  @protected
  Proof dco_decode_proof(dynamic raw);

  @protected
  SdJwtCredential dco_decode_sd_jwt_credential(dynamic raw);

  @protected
  SelectableCredential dco_decode_selectable_credential(dynamic raw);

  @protected
  TrustInfo dco_decode_trust_info(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VerifiableCredential dco_decode_verifiable_credential(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Credential sse_decode_box_autoadd_credential(SseDeserializer deserializer);

  @protected
  CredentialStatus sse_decode_box_autoadd_credential_status(
    SseDeserializer deserializer,
  );

  @protected
  MDocCredential sse_decode_box_autoadd_m_doc_credential(
    SseDeserializer deserializer,
  );

  @protected
  Proof sse_decode_box_autoadd_proof(SseDeserializer deserializer);

  @protected
  SdJwtCredential sse_decode_box_autoadd_sd_jwt_credential(
    SseDeserializer deserializer,
  );

  @protected
  TrustInfo sse_decode_box_autoadd_trust_info(SseDeserializer deserializer);

  @protected
  VerifiableCredential sse_decode_box_autoadd_verifiable_credential(
    SseDeserializer deserializer,
  );

  @protected
  Credential sse_decode_credential(SseDeserializer deserializer);

  @protected
  CredentialGroup sse_decode_credential_group(SseDeserializer deserializer);

  @protected
  CredentialStatus sse_decode_credential_status(SseDeserializer deserializer);

  @protected
  CredentialSubject sse_decode_credential_subject(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Credential> sse_decode_list_credential(SseDeserializer deserializer);

  @protected
  List<CredentialGroup> sse_decode_list_credential_group(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MDocCredential sse_decode_m_doc_credential(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CredentialStatus? sse_decode_opt_box_autoadd_credential_status(
    SseDeserializer deserializer,
  );

  @protected
  Proof? sse_decode_opt_box_autoadd_proof(SseDeserializer deserializer);

  @protected
  TrustInfo? sse_decode_opt_box_autoadd_trust_info(
    SseDeserializer deserializer,
  );

  @protected
  PrivacyLevel sse_decode_privacy_level(SseDeserializer deserializer);

  @protected
  Proof sse_decode_proof(SseDeserializer deserializer);

  @protected
  SdJwtCredential sse_decode_sd_jwt_credential(SseDeserializer deserializer);

  @protected
  SelectableCredential sse_decode_selectable_credential(
    SseDeserializer deserializer,
  );

  @protected
  TrustInfo sse_decode_trust_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VerifiableCredential sse_decode_verifiable_credential(
    SseDeserializer deserializer,
  );

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_credential> cst_encode_box_autoadd_credential(
    Credential raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_credential();
    cst_api_fill_to_wire_credential(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_credential_status>
  cst_encode_box_autoadd_credential_status(CredentialStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_credential_status();
    cst_api_fill_to_wire_credential_status(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_m_doc_credential>
  cst_encode_box_autoadd_m_doc_credential(MDocCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_m_doc_credential();
    cst_api_fill_to_wire_m_doc_credential(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_proof> cst_encode_box_autoadd_proof(Proof raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_proof();
    cst_api_fill_to_wire_proof(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_sd_jwt_credential>
  cst_encode_box_autoadd_sd_jwt_credential(SdJwtCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_sd_jwt_credential();
    cst_api_fill_to_wire_sd_jwt_credential(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_trust_info> cst_encode_box_autoadd_trust_info(
    TrustInfo raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_trust_info();
    cst_api_fill_to_wire_trust_info(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_verifiable_credential>
  cst_encode_box_autoadd_verifiable_credential(VerifiableCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_verifiable_credential();
    cst_api_fill_to_wire_verifiable_credential(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_credential> cst_encode_list_credential(
    List<Credential> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_credential(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_credential(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_credential_group> cst_encode_list_credential_group(
    List<CredentialGroup> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_credential_group(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_credential_group(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_list_prim_u_8_strict>
  cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_list_prim_u_8_strict(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_list_prim_u_8_strict(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_credential_status>
  cst_encode_opt_box_autoadd_credential_status(CredentialStatus? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_credential_status(raw);
  }

  @protected
  ffi.Pointer<wire_cst_proof> cst_encode_opt_box_autoadd_proof(Proof? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_proof(raw);
  }

  @protected
  ffi.Pointer<wire_cst_trust_info> cst_encode_opt_box_autoadd_trust_info(
    TrustInfo? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_trust_info(raw);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_credential(
    Credential apiObj,
    ffi.Pointer<wire_cst_credential> wireObj,
  ) {
    cst_api_fill_to_wire_credential(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_credential_status(
    CredentialStatus apiObj,
    ffi.Pointer<wire_cst_credential_status> wireObj,
  ) {
    cst_api_fill_to_wire_credential_status(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_m_doc_credential(
    MDocCredential apiObj,
    ffi.Pointer<wire_cst_m_doc_credential> wireObj,
  ) {
    cst_api_fill_to_wire_m_doc_credential(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_proof(
    Proof apiObj,
    ffi.Pointer<wire_cst_proof> wireObj,
  ) {
    cst_api_fill_to_wire_proof(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_sd_jwt_credential(
    SdJwtCredential apiObj,
    ffi.Pointer<wire_cst_sd_jwt_credential> wireObj,
  ) {
    cst_api_fill_to_wire_sd_jwt_credential(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_trust_info(
    TrustInfo apiObj,
    ffi.Pointer<wire_cst_trust_info> wireObj,
  ) {
    cst_api_fill_to_wire_trust_info(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_verifiable_credential(
    VerifiableCredential apiObj,
    ffi.Pointer<wire_cst_verifiable_credential> wireObj,
  ) {
    cst_api_fill_to_wire_verifiable_credential(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_credential(
    Credential apiObj,
    wire_cst_credential wireObj,
  ) {
    if (apiObj is Credential_VerifiableCredential) {
      var pre_field0 = cst_encode_box_autoadd_verifiable_credential(
        apiObj.field0,
      );
      wireObj.tag = 0;
      wireObj.kind.VerifiableCredential.field0 = pre_field0;
      return;
    }
    if (apiObj is Credential_MDoc) {
      var pre_field0 = cst_encode_box_autoadd_m_doc_credential(apiObj.field0);
      wireObj.tag = 1;
      wireObj.kind.MDoc.field0 = pre_field0;
      return;
    }
    if (apiObj is Credential_SdJwt) {
      var pre_field0 = cst_encode_box_autoadd_sd_jwt_credential(apiObj.field0);
      wireObj.tag = 2;
      wireObj.kind.SdJwt.field0 = pre_field0;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_credential_group(
    CredentialGroup apiObj,
    wire_cst_credential_group wireObj,
  ) {
    wireObj.issuer = cst_encode_String(apiObj.issuer);
    wireObj.issuer_name = cst_encode_String(apiObj.issuerName);
    wireObj.credentials = cst_encode_list_credential(apiObj.credentials);
    wireObj.logo_url = cst_encode_opt_String(apiObj.logoUrl);
  }

  @protected
  void cst_api_fill_to_wire_credential_status(
    CredentialStatus apiObj,
    wire_cst_credential_status wireObj,
  ) {
    wireObj.status_type = cst_encode_String(apiObj.statusType);
    wireObj.status_list_credential = cst_encode_opt_String(
      apiObj.statusListCredential,
    );
    wireObj.status_list_index = cst_encode_opt_String(apiObj.statusListIndex);
  }

  @protected
  void cst_api_fill_to_wire_credential_subject(
    CredentialSubject apiObj,
    wire_cst_credential_subject wireObj,
  ) {
    wireObj.id = cst_encode_opt_String(apiObj.id);
    wireObj.claims_json = cst_encode_String(apiObj.claimsJson);
  }

  @protected
  void cst_api_fill_to_wire_m_doc_credential(
    MDocCredential apiObj,
    wire_cst_m_doc_credential wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.doc_type = cst_encode_String(apiObj.docType);
    wireObj.issuing_authority = cst_encode_String(apiObj.issuingAuthority);
    wireObj.issuing_country = cst_encode_String(apiObj.issuingCountry);
    wireObj.expiry_date = cst_encode_opt_String(apiObj.expiryDate);
    wireObj.namespaces_json = cst_encode_String(apiObj.namespacesJson);
    wireObj.trust_info = cst_encode_opt_box_autoadd_trust_info(
      apiObj.trustInfo,
    );
    wireObj.portrait = cst_encode_opt_String(apiObj.portrait);
    wireObj.signature = cst_encode_opt_String(apiObj.signature);
  }

  @protected
  void cst_api_fill_to_wire_proof(Proof apiObj, wire_cst_proof wireObj) {
    wireObj.proof_type = cst_encode_String(apiObj.proofType);
    wireObj.created = cst_encode_opt_String(apiObj.created);
    wireObj.verification_method = cst_encode_opt_String(
      apiObj.verificationMethod,
    );
    wireObj.proof_purpose = cst_encode_opt_String(apiObj.proofPurpose);
    wireObj.proof_value = cst_encode_opt_String(apiObj.proofValue);
  }

  @protected
  void cst_api_fill_to_wire_sd_jwt_credential(
    SdJwtCredential apiObj,
    wire_cst_sd_jwt_credential wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.types = cst_encode_list_String(apiObj.types);
    wireObj.issuer = cst_encode_String(apiObj.issuer);
    wireObj.issuance_date = cst_encode_String(apiObj.issuanceDate);
    wireObj.expiration_date = cst_encode_opt_String(apiObj.expirationDate);
    wireObj.disclosed_claims_json = cst_encode_String(
      apiObj.disclosedClaimsJson,
    );
    wireObj.disclosable_claims = cst_encode_list_String(
      apiObj.disclosableClaims,
    );
    wireObj.key_binding = cst_encode_opt_String(apiObj.keyBinding);
  }

  @protected
  void cst_api_fill_to_wire_selectable_credential(
    SelectableCredential apiObj,
    wire_cst_selectable_credential wireObj,
  ) {
    cst_api_fill_to_wire_credential(apiObj.credential, wireObj.credential);
    wireObj.is_selected = cst_encode_bool(apiObj.isSelected);
    wireObj.selected_claims = cst_encode_list_String(apiObj.selectedClaims);
    wireObj.privacy_level = cst_encode_privacy_level(apiObj.privacyLevel);
  }

  @protected
  void cst_api_fill_to_wire_trust_info(
    TrustInfo apiObj,
    wire_cst_trust_info wireObj,
  ) {
    wireObj.is_valid = cst_encode_bool(apiObj.isValid);
    wireObj.trust_anchor = cst_encode_opt_String(apiObj.trustAnchor);
    wireObj.status_message = cst_encode_opt_String(apiObj.statusMessage);
    wireObj.certificate_chain = cst_encode_list_String(apiObj.certificateChain);
  }

  @protected
  void cst_api_fill_to_wire_verifiable_credential(
    VerifiableCredential apiObj,
    wire_cst_verifiable_credential wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.types = cst_encode_list_String(apiObj.types);
    wireObj.issuer = cst_encode_String(apiObj.issuer);
    wireObj.issuer_name = cst_encode_opt_String(apiObj.issuerName);
    wireObj.issuance_date = cst_encode_String(apiObj.issuanceDate);
    wireObj.expiration_date = cst_encode_opt_String(apiObj.expirationDate);
    cst_api_fill_to_wire_credential_subject(apiObj.subject, wireObj.subject);
    wireObj.proof = cst_encode_opt_box_autoadd_proof(apiObj.proof);
    wireObj.status = cst_encode_opt_box_autoadd_credential_status(
      apiObj.status,
    );
    wireObj.raw_json = cst_encode_opt_String(apiObj.rawJson);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_privacy_level(PrivacyLevel raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_credential(
    Credential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proof(Proof self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trust_info(
    TrustInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential(Credential self, SseSerializer serializer);

  @protected
  void sse_encode_credential_group(
    CredentialGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential_subject(
    CredentialSubject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_credential(
    List<Credential> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_credential_group(
    List<CredentialGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_credential_status(
    CredentialStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_proof(Proof? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_trust_info(
    TrustInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_privacy_level(PrivacyLevel self, SseSerializer serializer);

  @protected
  void sse_encode_proof(Proof self, SseSerializer serializer);

  @protected
  void sse_encode_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_selectable_credential(
    SelectableCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trust_info(TrustInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  );
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__create_selectable_credential(
    int port_,
    ffi.Pointer<wire_cst_credential> credential,
    int privacy_level,
  ) {
    return _wire__crate__api__create_selectable_credential(
      port_,
      credential,
      privacy_level,
    );
  }

  late final _wire__crate__api__create_selectable_credentialPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_credential>,
            ffi.Int32,
          )
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__create_selectable_credential',
      );
  late final _wire__crate__api__create_selectable_credential =
      _wire__crate__api__create_selectable_credentialPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_credential>, int)
          >();

  void wire__crate__api__credential_from_json(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> json,
  ) {
    return _wire__crate__api__credential_from_json(port_, json);
  }

  late final _wire__crate__api__credential_from_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__credential_from_json',
      );
  late final _wire__crate__api__credential_from_json =
      _wire__crate__api__credential_from_jsonPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__credential_to_json(
    int port_,
    ffi.Pointer<wire_cst_credential> credential,
  ) {
    return _wire__crate__api__credential_to_json(port_, credential);
  }

  late final _wire__crate__api__credential_to_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_credential>)
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__credential_to_json',
      );
  late final _wire__crate__api__credential_to_json =
      _wire__crate__api__credential_to_jsonPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_credential>)>();

  void wire__crate__api__get_credential_claims(
    int port_,
    ffi.Pointer<wire_cst_credential> credential,
  ) {
    return _wire__crate__api__get_credential_claims(port_, credential);
  }

  late final _wire__crate__api__get_credential_claimsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_credential>)
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__get_credential_claims',
      );
  late final _wire__crate__api__get_credential_claims =
      _wire__crate__api__get_credential_claimsPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_credential>)>();

  void wire__crate__api__group_credentials_by_issuer(
    int port_,
    ffi.Pointer<wire_cst_list_credential> credentials,
  ) {
    return _wire__crate__api__group_credentials_by_issuer(port_, credentials);
  }

  late final _wire__crate__api__group_credentials_by_issuerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_credential>)
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__group_credentials_by_issuer',
      );
  late final _wire__crate__api__group_credentials_by_issuer =
      _wire__crate__api__group_credentials_by_issuerPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_credential>)
          >();

  void wire__crate__api__is_credential_expired(
    int port_,
    ffi.Pointer<wire_cst_credential> credential,
  ) {
    return _wire__crate__api__is_credential_expired(port_, credential);
  }

  late final _wire__crate__api__is_credential_expiredPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_credential>)
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__is_credential_expired',
      );
  late final _wire__crate__api__is_credential_expired =
      _wire__crate__api__is_credential_expiredPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_credential>)>();

  void wire__crate__api__parse_mdoc_credential(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> cbor_bytes,
  ) {
    return _wire__crate__api__parse_mdoc_credential(port_, cbor_bytes);
  }

  late final _wire__crate__api__parse_mdoc_credentialPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__parse_mdoc_credential',
      );
  late final _wire__crate__api__parse_mdoc_credential =
      _wire__crate__api__parse_mdoc_credentialPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>)
          >();

  void wire__crate__api__parse_sd_jwt_credential(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sd_jwt,
  ) {
    return _wire__crate__api__parse_sd_jwt_credential(port_, sd_jwt);
  }

  late final _wire__crate__api__parse_sd_jwt_credentialPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__parse_sd_jwt_credential',
      );
  late final _wire__crate__api__parse_sd_jwt_credential =
      _wire__crate__api__parse_sd_jwt_credentialPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__parse_verifiable_credential(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> json,
  ) {
    return _wire__crate__api__parse_verifiable_credential(port_, json);
  }

  late final _wire__crate__api__parse_verifiable_credentialPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__parse_verifiable_credential',
      );
  late final _wire__crate__api__parse_verifiable_credential =
      _wire__crate__api__parse_verifiable_credentialPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__verify_and_attach_trust(
    int port_,
    ffi.Pointer<wire_cst_m_doc_credential> mdoc,
    ffi.Pointer<wire_cst_list_list_prim_u_8_strict> x5chain,
  ) {
    return _wire__crate__api__verify_and_attach_trust(port_, mdoc, x5chain);
  }

  late final _wire__crate__api__verify_and_attach_trustPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_m_doc_credential>,
            ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__verify_and_attach_trust',
      );
  late final _wire__crate__api__verify_and_attach_trust =
      _wire__crate__api__verify_and_attach_trustPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_m_doc_credential>,
              ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__verify_mdoc_trust_chain(
    int port_,
    ffi.Pointer<wire_cst_list_list_prim_u_8_strict> x5chain,
  ) {
    return _wire__crate__api__verify_mdoc_trust_chain(port_, x5chain);
  }

  late final _wire__crate__api__verify_mdoc_trust_chainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_privacyidea_authenticator_wire__crate__api__verify_mdoc_trust_chain',
      );
  late final _wire__crate__api__verify_mdoc_trust_chain =
      _wire__crate__api__verify_mdoc_trust_chainPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_list_prim_u_8_strict>)
          >();

  ffi.Pointer<wire_cst_credential> cst_new_box_autoadd_credential() {
    return _cst_new_box_autoadd_credential();
  }

  late final _cst_new_box_autoadd_credentialPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_credential> Function()>>(
        'frbgen_privacyidea_authenticator_cst_new_box_autoadd_credential',
      );
  late final _cst_new_box_autoadd_credential =
      _cst_new_box_autoadd_credentialPtr
          .asFunction<ffi.Pointer<wire_cst_credential> Function()>();

  ffi.Pointer<wire_cst_credential_status>
  cst_new_box_autoadd_credential_status() {
    return _cst_new_box_autoadd_credential_status();
  }

  late final _cst_new_box_autoadd_credential_statusPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_credential_status> Function()>
      >(
        'frbgen_privacyidea_authenticator_cst_new_box_autoadd_credential_status',
      );
  late final _cst_new_box_autoadd_credential_status =
      _cst_new_box_autoadd_credential_statusPtr
          .asFunction<ffi.Pointer<wire_cst_credential_status> Function()>();

  ffi.Pointer<wire_cst_m_doc_credential>
  cst_new_box_autoadd_m_doc_credential() {
    return _cst_new_box_autoadd_m_doc_credential();
  }

  late final _cst_new_box_autoadd_m_doc_credentialPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_m_doc_credential> Function()>
      >(
        'frbgen_privacyidea_authenticator_cst_new_box_autoadd_m_doc_credential',
      );
  late final _cst_new_box_autoadd_m_doc_credential =
      _cst_new_box_autoadd_m_doc_credentialPtr
          .asFunction<ffi.Pointer<wire_cst_m_doc_credential> Function()>();

  ffi.Pointer<wire_cst_proof> cst_new_box_autoadd_proof() {
    return _cst_new_box_autoadd_proof();
  }

  late final _cst_new_box_autoadd_proofPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_proof> Function()>>(
        'frbgen_privacyidea_authenticator_cst_new_box_autoadd_proof',
      );
  late final _cst_new_box_autoadd_proof = _cst_new_box_autoadd_proofPtr
      .asFunction<ffi.Pointer<wire_cst_proof> Function()>();

  ffi.Pointer<wire_cst_sd_jwt_credential>
  cst_new_box_autoadd_sd_jwt_credential() {
    return _cst_new_box_autoadd_sd_jwt_credential();
  }

  late final _cst_new_box_autoadd_sd_jwt_credentialPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_sd_jwt_credential> Function()>
      >(
        'frbgen_privacyidea_authenticator_cst_new_box_autoadd_sd_jwt_credential',
      );
  late final _cst_new_box_autoadd_sd_jwt_credential =
      _cst_new_box_autoadd_sd_jwt_credentialPtr
          .asFunction<ffi.Pointer<wire_cst_sd_jwt_credential> Function()>();

  ffi.Pointer<wire_cst_trust_info> cst_new_box_autoadd_trust_info() {
    return _cst_new_box_autoadd_trust_info();
  }

  late final _cst_new_box_autoadd_trust_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_trust_info> Function()>>(
        'frbgen_privacyidea_authenticator_cst_new_box_autoadd_trust_info',
      );
  late final _cst_new_box_autoadd_trust_info =
      _cst_new_box_autoadd_trust_infoPtr
          .asFunction<ffi.Pointer<wire_cst_trust_info> Function()>();

  ffi.Pointer<wire_cst_verifiable_credential>
  cst_new_box_autoadd_verifiable_credential() {
    return _cst_new_box_autoadd_verifiable_credential();
  }

  late final _cst_new_box_autoadd_verifiable_credentialPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_verifiable_credential> Function()
        >
      >(
        'frbgen_privacyidea_authenticator_cst_new_box_autoadd_verifiable_credential',
      );
  late final _cst_new_box_autoadd_verifiable_credential =
      _cst_new_box_autoadd_verifiable_credentialPtr
          .asFunction<ffi.Pointer<wire_cst_verifiable_credential> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_privacyidea_authenticator_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_credential> cst_new_list_credential(int len) {
    return _cst_new_list_credential(len);
  }

  late final _cst_new_list_credentialPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_credential> Function(ffi.Int32)
        >
      >('frbgen_privacyidea_authenticator_cst_new_list_credential');
  late final _cst_new_list_credential = _cst_new_list_credentialPtr
      .asFunction<ffi.Pointer<wire_cst_list_credential> Function(int)>();

  ffi.Pointer<wire_cst_list_credential_group> cst_new_list_credential_group(
    int len,
  ) {
    return _cst_new_list_credential_group(len);
  }

  late final _cst_new_list_credential_groupPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_credential_group> Function(ffi.Int32)
        >
      >('frbgen_privacyidea_authenticator_cst_new_list_credential_group');
  late final _cst_new_list_credential_group = _cst_new_list_credential_groupPtr
      .asFunction<ffi.Pointer<wire_cst_list_credential_group> Function(int)>();

  ffi.Pointer<wire_cst_list_list_prim_u_8_strict>
  cst_new_list_list_prim_u_8_strict(int len) {
    return _cst_new_list_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_privacyidea_authenticator_cst_new_list_list_prim_u_8_strict');
  late final _cst_new_list_list_prim_u_8_strict =
      _cst_new_list_list_prim_u_8_strictPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_list_prim_u_8_strict> Function(int)
          >();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_privacyidea_authenticator_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_privacyidea_authenticator_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_credential_subject extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> claims_json;
}

final class wire_cst_proof extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> proof_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> created;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> verification_method;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> proof_purpose;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> proof_value;
}

final class wire_cst_credential_status extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status_list_credential;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status_list_index;
}

final class wire_cst_verifiable_credential extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_String> types;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuer;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuer_name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuance_date;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> expiration_date;

  external wire_cst_credential_subject subject;

  external ffi.Pointer<wire_cst_proof> proof;

  external ffi.Pointer<wire_cst_credential_status> status;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> raw_json;
}

final class wire_cst_Credential_VerifiableCredential extends ffi.Struct {
  external ffi.Pointer<wire_cst_verifiable_credential> field0;
}

final class wire_cst_trust_info extends ffi.Struct {
  @ffi.Bool()
  external bool is_valid;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> trust_anchor;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status_message;

  external ffi.Pointer<wire_cst_list_String> certificate_chain;
}

final class wire_cst_m_doc_credential extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> doc_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuing_authority;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuing_country;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> expiry_date;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> namespaces_json;

  external ffi.Pointer<wire_cst_trust_info> trust_info;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> portrait;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signature;
}

final class wire_cst_Credential_MDoc extends ffi.Struct {
  external ffi.Pointer<wire_cst_m_doc_credential> field0;
}

final class wire_cst_sd_jwt_credential extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_String> types;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuer;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuance_date;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> expiration_date;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> disclosed_claims_json;

  external ffi.Pointer<wire_cst_list_String> disclosable_claims;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> key_binding;
}

final class wire_cst_Credential_SdJwt extends ffi.Struct {
  external ffi.Pointer<wire_cst_sd_jwt_credential> field0;
}

final class CredentialKind extends ffi.Union {
  external wire_cst_Credential_VerifiableCredential VerifiableCredential;

  external wire_cst_Credential_MDoc MDoc;

  external wire_cst_Credential_SdJwt SdJwt;
}

final class wire_cst_credential extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external CredentialKind kind;
}

final class wire_cst_list_credential extends ffi.Struct {
  external ffi.Pointer<wire_cst_credential> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_credential_group extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuer;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> issuer_name;

  external ffi.Pointer<wire_cst_list_credential> credentials;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> logo_url;
}

final class wire_cst_list_credential_group extends ffi.Struct {
  external ffi.Pointer<wire_cst_credential_group> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_selectable_credential extends ffi.Struct {
  external wire_cst_credential credential;

  @ffi.Bool()
  external bool is_selected;

  external ffi.Pointer<wire_cst_list_String> selected_claims;

  @ffi.Int32()
  external int privacy_level;
}
