// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'credential.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Credential dco_decode_box_autoadd_credential(dynamic raw);

  @protected
  CredentialStatus dco_decode_box_autoadd_credential_status(dynamic raw);

  @protected
  MDocCredential dco_decode_box_autoadd_m_doc_credential(dynamic raw);

  @protected
  Proof dco_decode_box_autoadd_proof(dynamic raw);

  @protected
  SdJwtCredential dco_decode_box_autoadd_sd_jwt_credential(dynamic raw);

  @protected
  TrustInfo dco_decode_box_autoadd_trust_info(dynamic raw);

  @protected
  VerifiableCredential dco_decode_box_autoadd_verifiable_credential(
    dynamic raw,
  );

  @protected
  Credential dco_decode_credential(dynamic raw);

  @protected
  CredentialGroup dco_decode_credential_group(dynamic raw);

  @protected
  CredentialStatus dco_decode_credential_status(dynamic raw);

  @protected
  CredentialSubject dco_decode_credential_subject(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Credential> dco_decode_list_credential(dynamic raw);

  @protected
  List<CredentialGroup> dco_decode_list_credential_group(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MDocCredential dco_decode_m_doc_credential(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CredentialStatus? dco_decode_opt_box_autoadd_credential_status(dynamic raw);

  @protected
  Proof? dco_decode_opt_box_autoadd_proof(dynamic raw);

  @protected
  TrustInfo? dco_decode_opt_box_autoadd_trust_info(dynamic raw);

  @protected
  PrivacyLevel dco_decode_privacy_level(dynamic raw);

  @protected
  Proof dco_decode_proof(dynamic raw);

  @protected
  SdJwtCredential dco_decode_sd_jwt_credential(dynamic raw);

  @protected
  SelectableCredential dco_decode_selectable_credential(dynamic raw);

  @protected
  TrustInfo dco_decode_trust_info(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VerifiableCredential dco_decode_verifiable_credential(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Credential sse_decode_box_autoadd_credential(SseDeserializer deserializer);

  @protected
  CredentialStatus sse_decode_box_autoadd_credential_status(
    SseDeserializer deserializer,
  );

  @protected
  MDocCredential sse_decode_box_autoadd_m_doc_credential(
    SseDeserializer deserializer,
  );

  @protected
  Proof sse_decode_box_autoadd_proof(SseDeserializer deserializer);

  @protected
  SdJwtCredential sse_decode_box_autoadd_sd_jwt_credential(
    SseDeserializer deserializer,
  );

  @protected
  TrustInfo sse_decode_box_autoadd_trust_info(SseDeserializer deserializer);

  @protected
  VerifiableCredential sse_decode_box_autoadd_verifiable_credential(
    SseDeserializer deserializer,
  );

  @protected
  Credential sse_decode_credential(SseDeserializer deserializer);

  @protected
  CredentialGroup sse_decode_credential_group(SseDeserializer deserializer);

  @protected
  CredentialStatus sse_decode_credential_status(SseDeserializer deserializer);

  @protected
  CredentialSubject sse_decode_credential_subject(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Credential> sse_decode_list_credential(SseDeserializer deserializer);

  @protected
  List<CredentialGroup> sse_decode_list_credential_group(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MDocCredential sse_decode_m_doc_credential(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CredentialStatus? sse_decode_opt_box_autoadd_credential_status(
    SseDeserializer deserializer,
  );

  @protected
  Proof? sse_decode_opt_box_autoadd_proof(SseDeserializer deserializer);

  @protected
  TrustInfo? sse_decode_opt_box_autoadd_trust_info(
    SseDeserializer deserializer,
  );

  @protected
  PrivacyLevel sse_decode_privacy_level(SseDeserializer deserializer);

  @protected
  Proof sse_decode_proof(SseDeserializer deserializer);

  @protected
  SdJwtCredential sse_decode_sd_jwt_credential(SseDeserializer deserializer);

  @protected
  SelectableCredential sse_decode_selectable_credential(
    SseDeserializer deserializer,
  );

  @protected
  TrustInfo sse_decode_trust_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VerifiableCredential sse_decode_verifiable_credential(
    SseDeserializer deserializer,
  );

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_credential(Credential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_credential(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_credential_status(CredentialStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_credential_status(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_m_doc_credential(MDocCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_m_doc_credential(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_proof(Proof raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_proof(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_sd_jwt_credential(SdJwtCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_sd_jwt_credential(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_trust_info(TrustInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_trust_info(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_verifiable_credential(VerifiableCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_verifiable_credential(raw);
  }

  @protected
  JSAny cst_encode_credential(Credential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is Credential_VerifiableCredential) {
      return [
        0,
        cst_encode_box_autoadd_verifiable_credential(raw.field0),
      ].jsify()!;
    }
    if (raw is Credential_MDoc) {
      return [1, cst_encode_box_autoadd_m_doc_credential(raw.field0)].jsify()!;
    }
    if (raw is Credential_SdJwt) {
      return [2, cst_encode_box_autoadd_sd_jwt_credential(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_credential_group(CredentialGroup raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.issuer),
      cst_encode_String(raw.issuerName),
      cst_encode_list_credential(raw.credentials),
      cst_encode_opt_String(raw.logoUrl),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_credential_status(CredentialStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.statusType),
      cst_encode_opt_String(raw.statusListCredential),
      cst_encode_opt_String(raw.statusListIndex),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_credential_subject(CredentialSubject raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.id),
      cst_encode_String(raw.claimsJson),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_credential(List<Credential> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_credential).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_credential_group(List<CredentialGroup> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_credential_group).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_list_prim_u_8_strict).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_m_doc_credential(MDocCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.docType),
      cst_encode_String(raw.issuingAuthority),
      cst_encode_String(raw.issuingCountry),
      cst_encode_opt_String(raw.expiryDate),
      cst_encode_String(raw.namespacesJson),
      cst_encode_opt_box_autoadd_trust_info(raw.trustInfo),
      cst_encode_opt_String(raw.portrait),
      cst_encode_opt_String(raw.signature),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_credential_status(CredentialStatus? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_credential_status(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_proof(Proof? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_proof(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_trust_info(TrustInfo? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_trust_info(raw);
  }

  @protected
  JSAny cst_encode_proof(Proof raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.proofType),
      cst_encode_opt_String(raw.created),
      cst_encode_opt_String(raw.verificationMethod),
      cst_encode_opt_String(raw.proofPurpose),
      cst_encode_opt_String(raw.proofValue),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sd_jwt_credential(SdJwtCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_list_String(raw.types),
      cst_encode_String(raw.issuer),
      cst_encode_String(raw.issuanceDate),
      cst_encode_opt_String(raw.expirationDate),
      cst_encode_String(raw.disclosedClaimsJson),
      cst_encode_list_String(raw.disclosableClaims),
      cst_encode_opt_String(raw.keyBinding),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_selectable_credential(SelectableCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_credential(raw.credential),
      cst_encode_bool(raw.isSelected),
      cst_encode_list_String(raw.selectedClaims),
      cst_encode_privacy_level(raw.privacyLevel),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_trust_info(TrustInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.isValid),
      cst_encode_opt_String(raw.trustAnchor),
      cst_encode_opt_String(raw.statusMessage),
      cst_encode_list_String(raw.certificateChain),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_verifiable_credential(VerifiableCredential raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_list_String(raw.types),
      cst_encode_String(raw.issuer),
      cst_encode_opt_String(raw.issuerName),
      cst_encode_String(raw.issuanceDate),
      cst_encode_opt_String(raw.expirationDate),
      cst_encode_credential_subject(raw.subject),
      cst_encode_opt_box_autoadd_proof(raw.proof),
      cst_encode_opt_box_autoadd_credential_status(raw.status),
      cst_encode_opt_String(raw.rawJson),
    ].jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_privacy_level(PrivacyLevel raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_credential(
    Credential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proof(Proof self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trust_info(
    TrustInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential(Credential self, SseSerializer serializer);

  @protected
  void sse_encode_credential_group(
    CredentialGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential_subject(
    CredentialSubject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_credential(
    List<Credential> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_credential_group(
    List<CredentialGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_m_doc_credential(
    MDocCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_credential_status(
    CredentialStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_proof(Proof? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_trust_info(
    TrustInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_privacy_level(PrivacyLevel self, SseSerializer serializer);

  @protected
  void sse_encode_proof(Proof self, SseSerializer serializer);

  @protected
  void sse_encode_sd_jwt_credential(
    SdJwtCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_selectable_credential(
    SelectableCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trust_info(TrustInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verifiable_credential(
    VerifiableCredential self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__create_selectable_credential(
    NativePortType port_,
    JSAny credential,
    int privacy_level,
  ) => wasmModule.wire__crate__api__create_selectable_credential(
    port_,
    credential,
    privacy_level,
  );

  void wire__crate__api__credential_from_json(
    NativePortType port_,
    String json,
  ) => wasmModule.wire__crate__api__credential_from_json(port_, json);

  void wire__crate__api__credential_to_json(
    NativePortType port_,
    JSAny credential,
  ) => wasmModule.wire__crate__api__credential_to_json(port_, credential);

  void wire__crate__api__get_credential_claims(
    NativePortType port_,
    JSAny credential,
  ) => wasmModule.wire__crate__api__get_credential_claims(port_, credential);

  void wire__crate__api__group_credentials_by_issuer(
    NativePortType port_,
    JSAny credentials,
  ) => wasmModule.wire__crate__api__group_credentials_by_issuer(
    port_,
    credentials,
  );

  void wire__crate__api__is_credential_expired(
    NativePortType port_,
    JSAny credential,
  ) => wasmModule.wire__crate__api__is_credential_expired(port_, credential);

  void wire__crate__api__parse_mdoc_credential(
    NativePortType port_,
    JSAny cbor_bytes,
  ) => wasmModule.wire__crate__api__parse_mdoc_credential(port_, cbor_bytes);

  void wire__crate__api__parse_sd_jwt_credential(
    NativePortType port_,
    String sd_jwt,
  ) => wasmModule.wire__crate__api__parse_sd_jwt_credential(port_, sd_jwt);

  void wire__crate__api__parse_verifiable_credential(
    NativePortType port_,
    String json,
  ) => wasmModule.wire__crate__api__parse_verifiable_credential(port_, json);

  void wire__crate__api__verify_and_attach_trust(
    NativePortType port_,
    JSAny mdoc,
    JSAny x5chain,
  ) => wasmModule.wire__crate__api__verify_and_attach_trust(
    port_,
    mdoc,
    x5chain,
  );

  void wire__crate__api__verify_mdoc_trust_chain(
    NativePortType port_,
    JSAny x5chain,
  ) => wasmModule.wire__crate__api__verify_mdoc_trust_chain(port_, x5chain);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__create_selectable_credential(
    NativePortType port_,
    JSAny credential,
    int privacy_level,
  );

  external void wire__crate__api__credential_from_json(
    NativePortType port_,
    String json,
  );

  external void wire__crate__api__credential_to_json(
    NativePortType port_,
    JSAny credential,
  );

  external void wire__crate__api__get_credential_claims(
    NativePortType port_,
    JSAny credential,
  );

  external void wire__crate__api__group_credentials_by_issuer(
    NativePortType port_,
    JSAny credentials,
  );

  external void wire__crate__api__is_credential_expired(
    NativePortType port_,
    JSAny credential,
  );

  external void wire__crate__api__parse_mdoc_credential(
    NativePortType port_,
    JSAny cbor_bytes,
  );

  external void wire__crate__api__parse_sd_jwt_credential(
    NativePortType port_,
    String sd_jwt,
  );

  external void wire__crate__api__parse_verifiable_credential(
    NativePortType port_,
    String json,
  );

  external void wire__crate__api__verify_and_attach_trust(
    NativePortType port_,
    JSAny mdoc,
    JSAny x5chain,
  );

  external void wire__crate__api__verify_mdoc_trust_chain(
    NativePortType port_,
    JSAny x5chain,
  );
}
