// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'status.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `has_nonempty_proof`, `has_type`, `parse_entry`, `parse_index`, `required_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<FrbStatusEntry>> parseStatusEntries({
  required String credentialStatusJson,
}) => RustLib.instance.api.crateStatusParseStatusEntries(
  credentialStatusJson: credentialStatusJson,
);

Future<FrbStatusDecision> evaluateBitstringStatus({
  required String entryJson,
  required String statusListCredentialJson,
}) => RustLib.instance.api.crateStatusEvaluateBitstringStatus(
  entryJson: entryJson,
  statusListCredentialJson: statusListCredentialJson,
);

@freezed
sealed class FrbStatusDecision with _$FrbStatusDecision {
  const factory FrbStatusDecision({
    required String purpose,
    required BigInt index,
    required bool asserted,
    required BigInt listSize,
  }) = _FrbStatusDecision;
}

@freezed
sealed class FrbStatusEntry with _$FrbStatusEntry {
  const factory FrbStatusEntry({
    required String id,
    required String purpose,
    required BigInt index,
    required String listUrl,
    required String entryJson,
  }) = _FrbStatusEntry;
}
